### ISSUE TITLE
(Concept needed) Make Brews overview customizable

### ISSUE THREAD

**Issue by silasg** [graphefruit/Beanconqueror#101]
Personally I'd like to be able to customize what parameters I can see in the Brews overview without needing to show the Details.

For example I don't care much about date and time of the brew and I don't use the Cupping feature. Therefore the space of the net diagram with the cupping results feels wasted for me. Also I think, some parameters could be collapsed without loosing information (see #99) or added (see #100) without loosing space. Personally I would also like to see profile information there (not only about pressure, see #97).

Other users might have other requirements, e.g brewing temperature,  so customization should offer great benefits for everyone. I think, a (not only) UI concept is needed, so this issue is probably more a kind of an epic than a user story.

**Comment by silasg** [comment]
<img width="391" alt="alt-brew-settings" src="https://user-images.githubusercontent.com/275404/94042673-2be7f900-fdcc-11ea-8a56-2c465877cc69.png">

<img width="391" alt="alt-brew-overview" src="https://user-images.githubusercontent.com/275404/94042414-d7dd1480-fdcb-11ea-8e88-3eb19b6a93fb.png">

Attached you can find an example that I currently use as a prototype. I tried to show all information that I personally want to see in a compact way. Please note, that this already includes the suggestion for in/out parameters in issue #99.

Code can be found at https://github.com/silasg/Beanconqueror/tree/altbrewview.

Of course I am aware that my personal requirements might not be useful for anyone else. So a user must be able to customize more than just choose between "default" and "alternative" view. This screenshot and code is just meant to be a contribution to the discussion and as an example for what a use might want.

**Comment by graphefruit** [comment]
The wish now becomes real :)
In the next version 6.1 the values can be customized for each preparation method
