### ISSUE TITLE
Feature: make Beans customizable, like brewing parameters

### ISSUE THREAD

**Issue by silasg** [graphefruit/Beanconqueror#112]
After adding the processing to Beans (see #98) there are other ideas for new fields: Region, Height/MASL, Cupping Score, Farm, Harvest, Bean Pattern (? "Bohnenbild") and maybe even more.

If those are added, a feature to show/hide certain fields when creating, updating and showing bean details would be needed. Maybe one also wants to change the order of fields (I personally would not need this).

**Comment by graphefruit** [comment]
Hello @silasg,
it took some time, but this is now possible with 6.4., I'll close this issue so.
If you got any more requests for this kind of type, please open up a new ticket
