### ISSUE TITLE
Feature: time between brewing and drinking

### ISSUE THREAD

**Issue by papaGregor** [graphefruit/Beanconqueror#138]
Please add a data point for how long the user waited to drink the coffee after brewing it. Thank you!

**Comment by graphefruit** [comment]
Thanks for your request, 
is there any real use case for this?
Is this rather for cupping or really for brewing and / or serving? 

Adding data points is not the problem, its rather that another user understands the use case of this and can use it along the way

**Comment by papaGregor** [comment]
Ah, ok, I see. Well, I have found that what I am able to taste in the cup varies based on how hot the coffee is, so I am experimenting with how long I wait between brewing and drinking to try to find out if there’s an amount of time (as a proxy for temperature drop) that produces a difference in taste that I prefer.

For example, so far I’ve noticed that drinking within 2 min (a suggestion I’ve seen in some places) makes the coffee too hot for me to notice a lot of the flavor. Lately I’ve been playing with anywhere from 4–10 minutes (depending on some variations in the process I use), and I’ve noticed a lot of difference in what I taste and how enjoyable I find the coffee (leaving aside the idea of accidentally letting it get too cool :-)

Anyway, once I narrow that down, I can use it to further tweak the other parts of the process (grind size, brew time, etc) to see how/if changing one of those alters what I taste in the cup at 2m30s (or whatever) after brewing.

I suppose I’d consider it a cupping issue because the wait time alters what I taste in the cup, but I wouldn’t care if it’s grouped with brewing.

I hope all of what I’ve said makes sense, and that it addresses the issue of use-case for other users. What do you think?

**Comment by graphefruit** [comment]
Thanks for your suggestion.
I got the intention, but there will be a bit of flow which needs to be implemented.
So rather not in the next upcoming version

**Comment by graphefruit** [comment]
This ticket is pretty old, and there was no questions regarding this feature.
I'll close this one as not planned right now.
If needed, please open up a new one.
Have a great cup of coffee
Lars
