### ISSUE TITLE
Feature: HealthKit integration for caffeine consumption

### ISSUE THREAD

**Issue by papaGregor** [graphefruit/Beanconqueror#139]
It would be nice if the app could add the estimated caffeine consumed (based on grams of beans ground and brewing method, I’d imagine) to the Health app in iOS. I don’t know how much work this would take… It would be nice, but the other suggestions I made are higher-priority, in my opinion. Thanks!

**Comment by graphefruit** [comment]
Sounds great!
You know if there is an alternative on android?
Also you know how the caffeine is calculated by espresso/filter?

**Comment by papaGregor** [comment]
It might be simplest to just have the user provide the data, but if you want to include calculations / estimates, I’ve further discussed that below.

Not familiar with Android, so I don’t know for sure. It looks like Samsung Health did have caffeine-intake tracking as of 2019 but will lose it as of v6.11. Not sure if Google Fit has it natively yet, but I did find this plugin framework that supports caffeine intake as nutrition data on Android:

https://github.com/dariosalvi78/cordova-plugin-health

Regarding the caffeine quantity, I’ve found several answers. The most definitive seems to be to use UV spectroscopy, though I’m not sure how widely or cheaply available the equipment for that would be. Some people have been experimenting lately with refractometers to measure dissolved solids and thus calculate caffeine content per brew themselves. The USDA has guidelines (just Google “caffeine espresso” for an example), but various factors beyond brew method seem to affect the amount significantly. For the layperson, there are various websites and apps that provide estimates, but they sometimes disagree and seem to be the most basic method of quantifying for the coffee consumer. 

Regarding estimated calculations, though, I did find a couple of good answers:

How can I figure out how much caffeine is in my cup?
https://coffee.stackexchange.com/questions/79/how-can-i-figure-out-how-much-caffeine-is-in-my-cup

How much caffeine in coffee cup? Effects of processing operations, extraction methods and variables
Carla Severini, Antonio Derossi, Ilde Ricci, Anna Giuseppina Fiore and Rossella Caporizz
https://unaq-my.sharepoint.com/personal/5715_soyunaq_mx/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F5715%5Fsoyunaq%5Fmx%2FDocuments%2FLife%2Fshitty%20projects%2F55623%2Epdf&parent=%2Fpersonal%2F5715%5Fsoyunaq%5Fmx%2FDocuments%2FLife%2Fshitty%20projects&originalPath=aHR0cHM6Ly91bmFxLW15LnNoYXJlcG9pbnQuY29tLzpiOi9nL3BlcnNvbmFsLzU3MTVfc295dW5hcV9teC9FVFhDWGQ0QnBGdEVwMUxZSFZtZ2dvSUJEVEpGQ2xlMUR2V3E5UnZfYzFzbmJRP3J0aW1lPTFyRG1sS0tLMkVn

Perhaps it would be best to have the app provide, at most, an estimate based on brewing method, arabica/robusta ratio, etc, that could be overridden per brew by the user. Otherwise, the user could just manually enter the amount of caffeine per brewing method, bag of beans, or brew (cascading overrides, as in CSS). (The latter would probably be better for people doing their own calculations, anyway.)

Hope this is helpful and not somehow overbearing. Just trying to be thorough in my responses. Given the level of detail the app provides, I’ve guessed that that would be appreciated.  :-)

**Comment by graphefruit** [comment]
Thanks for your feedback.
I really appreciate the long and detailed feedback!

Sorry for the long delay.
The feature will not be implemented in the next version, rather the version next.

**Comment by graphefruit** [comment]
Hello @papaGregor I've done the first Integration and checked it.
Its now possible to write to HealthKit.
The existing problem is still after reading the caffeine examples, there is no "rule" to calculate it.
Rather it said: 12grams of beans = 120mg of caffeine.
This could be a simple calulation.

I won't force the user to edit their caffeine consumtion by hand, rather have a normal caffeine value, is this a solution which would be in your interest aswell?

**Comment by papaGregor** [comment]
Yeah, I think having a default caffeine value is fine. For the users who are measuring more specifically than I am (refractometers, etc), would it be possible to allow the user to override that default calculation when logging a particular brew? That way people aren't forced to calculate it but can if they want to. What do you think?

**Comment by graphefruit** [comment]
I need to think about how this could be achieved in a good way.
One way could be a standard text-field which will be filled and can be filled.

But I really don't like this solution, because caffeine shouldn't be a real value users track as a parameter to optimize their brew.
Giving a user always a popup to enter a custom coffeine value if they want to is one more click which should not be necessary.

**Comment by graphefruit** [comment]
I've added the feature now, the caffeine is calcualted by the multiplier 0.08 now.
The caffeine consumption is added automatically when saving the brew and the feature is activated in settings.

When there are some more requests by users to track the correct level of caffeine there will be another ticket to add this feature.
At this point I think its the best way to go.
![image](https://user-images.githubusercontent.com/6260244/104361650-087bc200-5513-11eb-8fee-0347c03f3780.png)

![image](https://user-images.githubusercontent.com/6260244/104358345-9a350080-550e-11eb-9e97-3e3e403dfb20.png)
![image](https://user-images.githubusercontent.com/6260244/104358408-b2a51b00-550e-11eb-9f09-cf89caf39371.png)

**Comment by graphefruit** [comment]
This feature will be available in the next update launching soon.
Thanks for your request!

**Comment by papaGregor** [comment]
Thank you! I appreciate it. 

On Jan 12, 2021, at 11:16 AM, Lars Saalbach ***@***.***> wrote:

﻿
I've added the feature now, the caffeine is calcualted by the multiplier 0.08 now.
The caffeine consumption is added automatically when saving the brew and the feature is activated in settings.

When there are some more requests by users to track the correct level of caffeine there will be another ticket to add this feature.
At this point I think its the best way to go.
