### ISSUE TITLE
Feature: cupping graph in Brew Details

### ISSUE THREAD

**Issue by papaGregor** [graphefruit/Beanconqueror#140]
If cupping data has been entered, it would be nice to see that data in the Details portion of the brew as well. Also, choosing Cupping means that the data is editable, which I’ve found it’s easy to do accidentally. Thanks!

**Comment by graphefruit** [comment]
I'll have a look how the graph can be entered into details.
Thanks for your request!

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/100525063-d3fbb300-31bd-11eb-9f33-df29ad9fdfcc.png)
Added in the next version
