### ISSUE TITLE
Titel covered after first Install

### ISSUE THREAD

**Issue by benjaminburkhardt** [graphefruit/Beanconqueror#155]
After installing and setting up the app, the title (on all pages) is covered. 

![8032DCCA-7779-4E2E-B56A-C63C515FD1C4](https://user-images.githubusercontent.com/18308827/104204143-3c7cb780-542d-11eb-90c0-29dbbec1138f.png)

BTW: Nice Idea!

**Comment by graphefruit** [comment]
Hey @benjaminburkhardt sorry for this!
Can you tell me your iOS Version and your device type?

**Comment by benjaminburkhardt** [comment]
I'm on the latest iOS 14.3 on an iPhone 12 mini.

**Comment by graphefruit** [comment]
Thanks I'll look on the emulator at the problem

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/104215248-ced68880-5438-11eb-92ba-aa67a708b00e.png)
I cant reproduce this issue on my emulator. (see attachment)

Is this issue disappearing when you rotate your device? 
Whats happening when you try to add an bean (overlay e.g.)? 
Do you have any scaling mechanism active on your phone (like font scaling etc?)

**Comment by benjaminburkhardt** [comment]
Did not disappear when turning or switching between pages - but disappeared after restarting the app...

**Comment by graphefruit** [comment]
Thanks for the hint, maybe its because of the "starting" screen, I'll have a look again here

**Comment by graphefruit** [comment]
Sorry @benjaminburkhardt I can't reproduce this issue.
I'll add on the next update an safe-space area aswell on the top area which i already did on the bottom now.
Maybe this will help that this issue will not be appear again, else if you can repeat this issue (like removing and installing the app again) I'd be happy to hear, else it looks like a hiccup.
Sorry for the inconvenience

**Comment by graphefruit** [comment]
I've made changes now, if this error will reoccure please reopen an ticket if this issue will occure again.
