### ISSUE TITLE
Customizable charts

### ISSUE THREAD

**Issue by sebastian-tischer** [graphefruit/Beanconqueror#156]
Hi Lars,

at first huge thanks for this amazing app - I love to use it daily 👍 

The only thing I am missing - which currently leads to double usage of excel + app - is to have custom charts/statistics in the app.

I like to combine the values of parameter and create various charts. Optimal would be, if you could implement a chart library and let the user combine the variables as they want.

I like to see my best brews and the relation to the parameters like grind settings, temperature, pressure in combination with the roast of the beans - to find out best settings.

Do you think this is possible?

Warm regards and thank you! :)
Sebastian

**Comment by graphefruit** [comment]
Hi Sebastian,
great to hear that feedback and your love to coffee :)

Actually I added a small excel-export in a first version to get more benefits out for the power users.
The statistic page aswell the cupping-radar uses ChartJS (Maybe you know this one)

Maybe you can give me more input about which information you'd like to evaluate inside the app.
Also I think you'd like to see the information inside the statistic page or something else?

I think there could be a possibility but just if I know the "exact" use case for this request.

Or maybe the excel-export would be already this what you're looking for? Which could be uploaded and in reference to this the different generated charts by excel?

Greetings 
Lars

**Comment by sebastian-tischer** [comment]
Hi Lars,

you are simply amazing, thank you for the fast and very open-minded reply :)

What I like to achieve basically is to find out what settings for which bean roast type I got the best brews with my espresso machine.

I thought about two ways:

1.) We together define a set of charts / use cases to mirror in the statistics view

2.) If possible we/you implement a open chart library where the user can define the parameters/variables he likes to use in a chart like:

- Define chart type (plot, line, cake...)
- Define the parameters for the chart (pressure, stars of the brew, roast type, grind setting) on which axis
- Then the chart gets created based on the defined parameters

I think the second option is better for the user since everybody can decide which stats he wants but more complicated to develop for you.

I am here to help with everything here, from concept, requirements, layout, testing etc. - up to you if you need help :)

Warm regards my friend!
Sebastian

**Comment by graphefruit** [comment]
Hi Sebastian,

thanks for the detailed feedback.
Sound like a good way, I like both ways.
I'm thinking about a way like on the preparation methods:
Creating a custom chart, and having predefined charts.

I'd propose we set up a meeting in February.
Before I think there will be no time for me.
Actually I develop 2 new features:
1. Homeroast section 
2. Cupping section

Specially the homeroast section has the first priority.

So if the time plan would be ok for you, I'd set up a meeting in the evening (UTC/GMT Berlin) to discuss the first version.

Just wanting to say: I develop and maintain this on my own, so giving specific time frames when a feature will be ready to ship or be under develop is not that easy.

Best regards
Lars

**Comment by sebastian-tischer** [comment]
Hi Lars,

sounds wonderful - you define the timeframe, I am here to help with whatever you need.

If you need some help in the meantime with testing or anything else - give me a call or write me a message to have a chat earlier:

https://sebastian.tischer.io/

Warm regards :)
Sebastian

**Comment by sebastian-tischer** [comment]
@graphefruit I just had some more ideas concerning the charts and statistics incl. taste categorization of the shot like here

![01](https://user-images.githubusercontent.com/63227608/106395921-24cd9900-6405-11eb-8403-fff7c1b0f86e.png)
![02](https://user-images.githubusercontent.com/63227608/106395922-26975c80-6405-11eb-9641-266fec6c3392.png)

If you like someone to work closer with you on the features and concepts I can't wait to jump on a call ;)

**Comment by graphefruit** [comment]
Beanconqueror won't do any customizeable charts in the near future, some users did own statistics solutions, which should be used for this.
I gonna close this issue.
If you got any more requests, please just open up a new one
