### ISSUE TITLE
Bitte Markgrad und mahldauer hinzufügen

### ISSUE THREAD

**Issue by GoProAndy** [graphefruit/Beanconqueror#159]
Hallo,
Ich würde gern zusätzlich zum Mahlgrad auch die Mahldauer bei den Bezügen eingeben können. Ich kann bei meinen Mühlen nur den Grad und die Anzahl von Sekunden wo gemahlen werden soll einstellen.
Danke
Andy

**Comment by graphefruit** [comment]
Hallo Andy,
über das Navigationsmenü kannst du auf die Brühparameter zugreifen.
Dort kannst du die Parameter Verwalten.
Dort gibt es auch den "Mühlen Timer" wo du die Zeit hinterlegen kannst.
Ich hoffe das ist die erwünschte Funktion.
Melde dich gerne zurück!
Viele Grüße in den Sonntag
Lars

**Comment by graphefruit** [comment]
Hallo @GoProAndy,
Konnte sich dein Thema auflösen?
Danke fürs Feedback!
Gruß
Lars

**Comment by graphefruit** [comment]
Hallo @GoProAndy,

ich schließe diesen Fall nun, falls du weitere Fragen / Probleme hast, mach gerne einen weiteren Issue auf.
Viele Grüße
Lars
