### ISSUE TITLE
Beschriftung korrigieren

### ISSUE THREAD

**Issue by MircoRa** [graphefruit/Beanconqueror#162]
Beim Bezug muss es "Gib deinen Mahlgrad ein" heißen und nicht "Gebe". Danke :)

**Comment by graphefruit** [comment]
Hallo @MircoRa,
danke für die Meldung, schaue ich mir an!
Gruß in den Sonntag

**Comment by graphefruit** [comment]
Hallo @MircoRa , die Labels wurden abgeändert.
Danke für die Meldung!
Gruß
Lars
