### ISSUE TITLE
Repeating a blended bean copies only the first bean sort

### ISSUE THREAD

**Issue by benedetto** [graphefruit/Beanconqueror#171]
### Expected behavior
If I chose "repeat" on a bean entry, I get a full/exact copy of the chosen item.

### Actual behavior
For a blend with two bean sorts the new entry contains only the first bean sort.

### Steps to reproduce
1. Create a bean of type blend with two bean sorts.
2. Chose "repeat" from the three dots menu
3. The newly created bean entry contains only the first sort in the blend list.

### Version information
5.1.0 for Android, downloaded from https://github.com/graphefruit/Beanconqueror/releases/tag/v.5.1.0

**Comment by graphefruit** [comment]
Hello @benedetto,
Thanks for reporting this issue.
I've found the problem and already fixed it! :)
Greetings
Lars
