### ISSUE TITLE
Options for defaults of "Preset Values" are not applied correctly.

### ISSUE THREAD

**Issue by benedetto** [graphefruit/Beanconqueror#175]
If I activate "Preset values" in the brew parameters settings to preset them with the values from the last brew, some of the values that should be preset according to the options are not, while others that should not be preset, are.

### Steps to reproduce
1. Activate "Preset Values" in the Brew Parameters menu
2. In the parameter list below, select "Coffee Type" and deselect "Beverage Quantity"
3. Create a new brew entry

### What happens
In the new brew entry,
- "Coffee Type" is empty even if it contained something in the brew before
- "Beverage Quantity" is preset with the value from the last brew entry.

I haven't checked systematically how other options behave, but for those two it happens for me.

**Comment by graphefruit** [comment]
Hi there!
Thanks for your report.
I'll have a look.
Can you exclude that custom parameters of the preparation type is not activated?
Else These would overwrite the settings.

**Comment by benedetto** [comment]
custom parameters of the preparation type was activated. After deactivating those, everything seems to work as expected... Looks like this was the culprit.
