### ISSUE TITLE
Edited grind setting does not show up

### ISSUE THREAD

**Issue by tokenstar** [graphefruit/Beanconqueror#186]
I made a brew with grind setting Test1 and then edited the brew changing the grind setting to Test2 but when viewing the brew it showed the old setting Test1. Force quitting the app and restarting, it shows up as Test2, so this seems to be a view refreshing issue.

**Comment by graphefruit** [comment]
Hi @tokenstar,

thanks for reporting this issue and digging deeper into the issue.
I've already watched this one and its fixed here: https://github.com/graphefruit/Beanconqueror/issues/181

The Version 5.3 will be released I think just after easter so there shouldn't be to much waiting time for this to be fixed.
Thanks for your patience and keep up a good brew every time! :)

I'll let this topic open until release, so you can prove that its working afterwards.

Greetings
Lars

**Comment by tokenstar** [comment]
Lars, Appreciate the quick response! I checked open issues but not closed ones fwiw. Just started using the app today, thanks for something really useful!

**Comment by graphefruit** [comment]
No worries!
The app is still small with a growing community.
I appreciate every feedback, shows me that the coffee lover is really digging deep into :)
If you just edit via the tripple dot "..." the issue won't be there, because its just a ui-refresh thing (small but still with a big impact)
Enjoy your saturday!

**Comment by graphefruit** [comment]
Hi @tokenstar,
can you recheck this case please? So this topic can be closed?
Thanks 
Lars

**Comment by tokenstar** [comment]
works now!
