### ISSUE TITLE
Feature request: Allow scores to be out of 10 (or custom range?)

### ISSUE THREAD

**Issue by tokenstar** [graphefruit/Beanconqueror#188]
5 stars is restrictive. When trying different brew params with the same bean they might all be 3 out of 5 stars overall, but I still want to differentiate a bit. I personally have been using scores out of 10 with 1 decimal place.

**Comment by graphefruit** [comment]
Hi @tokenstar,
In the history of this app there where several different approaches for brew ratings, thats why I think about rather the custom-range possibility, which would allow the user to use -1 to 5 for the start, and if someone likes rating from -1 to 10, less or more he can change this customizeable for himself.
Is this a direction you're request would fit into?

**Comment by tokenstar** [comment]
Sorry I don't understand the question well. If the question is " what if the user could specify a different max than 5 in the settings, eg they could pick 100 or 10" then the answer is yes that would satisfy my suggestion.

**Comment by tokenstar** [comment]
Sorry I don't understand the question well. If the question is " what if the user could specify a different max than 5 in the settings, eg they could pick 100 or 10" then the answer is yes that would satisfy my suggestion.

**Comment by graphefruit** [comment]
Sorry German-English, I try to prep up again:

I'd see a solution in the app-settings, where the user can set his own rating range.
The normal standard (when the app is installed) is -1 to 5, and everyone can change this settings from -1 to X, where X cant be less 5 (to meet the actual requirements)

**Comment by tokenstar** [comment]
Yes that sounds great. I'm hoping x can go up to 100

Pls don't apologise as my German is nonexistent.

**Comment by graphefruit** [comment]
In settings the user can now define a custom number between 5 to 100 (100 is the maximum)
When not changed (>5) then the normal star rating will be used and displayed.
Above 5 a badge-icon will visible for the rating
The brew can be filtered.

Keep in mind: If you rate a brew 80 and afterwards you change in settings the maximum brew rating to 70 your brew will be not visible anymore, there is no auto update.
