### ISSUE TITLE
Brew time/date not editable for standard parameters

### ISSUE THREAD

**Issue by benedetto** [graphefruit/Beanconqueror#199]
Due to the discussion in #175 I switched my parameter settings back to standard instead of custom parameters. Now I found out why I had switched to custom parameters in the first place:

When I use standard parameters, I am not able to set the time and date of the brew as editable parameters.

My use case: sometimes when I just have time to fetch a quick coffee between two video call meetings (home office times, you know), I don't launch the app while I make my coffee. Instead I just read and remember the relevant parameters to enter them later (e.g. during the next meeting, but sometimes also some hours later). Since I cannot edit the time stamp, they end up at some unrealistic times sometimes and I would like to correct them to be at least roughly where the actual brew time was.

For me, it must not necessarily be possible to edit the time while I enter the brew. It would be sufficient, if I just could correct the time via the edit menu, if that makes things easier.

**Comment by graphefruit** [comment]
Hi @benedetto,
sorry for the delayed response.
I'll dig into this case and come back here!
Thanks for reporting
Greetings
Lars

**Comment by graphefruit** [comment]
Hi @benedetto 
I just tried this on my own and its working without problems.
May it be possible that you pass me your beanconqueror.json dump from your settings?
You can send me them via email: lars.saalbach@beanconqueror.com
So I can exactly use your data to evaluate this case
Thanks in advance
Lars

**Comment by graphefruit** [comment]
Hi @benedetto, can this case be closed after we have wrote by email?

Greetings
Lars

**Comment by benedetto** [comment]
@graphefruit yes, it can. Now everything works as expected.
