### ISSUE TITLE
Show relative time since brew

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#22]
Currently we're displaying the roast time/date, but instead (optional) or in addition we could have a relative time such as "2 days ago".

https://github.com/date-fns/date-fns can easily do this with distanceInWords

**Comment by graphefruit** [comment]
Won't do this for now.
Is a nice to have enhancement.

**Comment by graphefruit** [comment]
This feature was idle for long time, so closed.
If needed please reopen a new ticket.
