### ISSUE TITLE
Feature Request: 12hr Time Option

### ISSUE THREAD

**Issue by nhadler** [graphefruit/Beanconqueror#224]
Hi,

I wanted to know if it was possible to get the times on the brews to also have the option to be in 12hr time instead of 24?

**Comment by graphefruit** [comment]
Hi @nhadler thanks for your feedback and feature request.
I haven't had a look in depth into this detail, but I can't see a real benefit of supporting both time formats.
I'll put this in backlog, but at the actual point given I've got to less time for developing this feature.
Thanks for your understandig
Lars

**Comment by mike1808** [comment]
@graphefruit I've seen this request few times in Espresso Aficionado discord. I think, the right thing to do to is to use the system locale for dates and time.

**Comment by graphefruit** [comment]
After the possibility was added to change the date format to like US format, and there wasn't any feedback since then that user asked for a 12hr format, I close this ticket as not planned right now.
If needed, please open up a new one.
