### ISSUE TITLE
not compatible with Android on Chromebook

### ISSUE THREAD

**Issue by dulitz** [graphefruit/Beanconqueror#239]
Google Play store indicates that the app is not compatible with my device (Google Pixelbook, stable channel).

See https://developer.android.com/topic/arc -- I haven't dug into the BC build...

**Comment by graphefruit** [comment]
Hello @dulitz,
thank your your request.

After I don't have a Google Pixelbook I cant help out here.
But I'm happy to answer your questions and help you along.

Greetings
Lars

**Comment by graphefruit** [comment]
This topic has been idle for long, I gonna close this now
