### ISSUE TITLE
iCloud Sync

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#24]
https://github.com/alexdrel/cordova-plugin-icloudkv

**Comment by DeastinY** [comment]
It might be possible to automagically enable iCloud sync with just some flags.

**Comment by DeastinY** [comment]
**Config.xml: **

BackupWebStorage(string) | Default: cloud  Allowed values: none, local, cloud.     Set to cloud to allow web storage data to backup via iCloud. Set to  local to allow only local backups via iTunes sync. Set to none prevent  web storage backups.
-- | --

**Comment by DeastinY** [comment]
Quote from Apple documentation:

> Change log files for a SQLite database (a SQLite database’s store file must never be stored in iCloud)

**Comment by graphefruit** [comment]
This won't be developed in near future on my side  sorry

**Comment by graphefruit** [comment]
This feature was idle for long time, so closed.
If needed please reopen a new ticket.
