### ISSUE TITLE
Brew time is not contained in xlsx export

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#241]
I just exported my library to excel but I can not find the brew time in there.
I have different brew parameters for V60, Aeropress and Espresso set - is this a problem?
The headers of the file are:
```
Mahlgrad | Kaffeemehl (gr) | Brühtemperatur | Brühmethode | Bohnensorte | Mühle | Mühlengeschwindigkeit (rpm) | Mühlen Timer | Profil | Brühmethoden Tools | Temperatur Zeit | Blooming-Zeit / Preinfusion | Erster Kaffeetropfen | Wassermenge (gr/ml) | Kaffeetyp | Kaffee-Konzentration | Bewertung | Notizen | Getränkmenge (gr/ml) | Gelöste Stoffe (TDS [%]) | Extraction Yield % | Uhrzeit (des Bezuges) | Brührate | Bohnenalter (Tage) | Archiviert | Bohnen ID | Brühmethoden Id | Mühlen Id
```

I'm using Version 5.4.0 on Android 10 from Google Play.
I can provide other information as well if you need them.

**Comment by graphefruit** [comment]
Hey @reox,
Brew time actually is not included (seems like I forgot this parameter).
I'll add this one in the next update.

Thank you for reporting!
Lars

**Comment by graphefruit** [comment]
Fixed in the next update
