### ISSUE TITLE
Show brewratio in g/l for filter

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#244]
I think I go with James Hoffmann, that for filter the 1:x brew ratios are a bit "ugly" to use. I would prefer to see this as g/l instead of the 1:x ratios. However, for espresso I still like the 1:x ratios. Having this configurable would be very nice.

Furthermore, having this in the brewratio calculator would be also nice, i.e. converting from ratios to g/l and calculating required dose for given yield and vice versa.

**Comment by reox** [comment]
yes, that is nothing of high importance :) And I like the dual display as well!

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/131232545-65f54dec-d9dd-4043-8514-d439e00b5484.png)
I've added the solution now as a dual display.
