### ISSUE TITLE
Bean age is calculated using time and not only the date component

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#254]
This is a minor flaw: the bean age seems to be calculated using the time when adding the bean and not simply by using the dates. thus adding two beans at different times at the day results in different ages:
![image](https://user-images.githubusercontent.com/431045/131802757-6a152371-111a-4a7d-a62b-1557cbe1e872.png)

To reproduce: Add two beans with the same roasting date at different times of the day. In the time between the two adds, the roast age will show one day offset.

**Comment by graphefruit** [comment]
Hi @reox, thanks for the report.
Could you please pass me your .JSON-Export file to reproduce this?
I couldn't on my side.

info@beanconqueror.com

Thanks! 
Lars

**Comment by graphefruit** [comment]
Fixed in next version.
Thanks for the information and reporting!
