### ISSUE TITLE
Can’t scroll through preparation methods

### ISSUE THREAD

**Issue by nhadler** [graphefruit/Beanconqueror#257]
Hi,

![image](https://user-images.githubusercontent.com/3527739/132960555-2fde4f0f-95e2-48e5-b3e7-4e8f07147982.jpeg)

With this clipped on the right side, I can't swipe to see the cut off portion.

**Comment by graphefruit** [comment]
Hi @nhadler,

thanks for the report, I gonna have a look!
Greetings

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/133490304-bebc5b0a-819f-474f-b35c-e1f7fb56e1e8.png)
Fixed :)
