### ISSUE TITLE
Add possibility to repeat old brew

### ISSUE THREAD

**Issue by stefanheyder** [graphefruit/Beanconqueror#26]
At the moment the user can repeat the last brew by activating the corresponding setting in the menu. For people using different brew methods (e.g. filter and espresso) it would be nice to be able to repeat a past brew. 

One could add a button to the brews view that presets the parameters of this brew.

**Comment by stefanheyder** [comment]
#31 introduces this option

**Comment by graphefruit** [comment]
Feature exists.
