### ISSUE TITLE
EY formula incorrect for total immersion brew

### ISSUE THREAD

**Issue by diskox** [graphefruit/Beanconqueror#262]
params:

- I’ve set up Clever Dripper as a full immersion method 
- brew 15g, water 245g, beverage weight 200g, tds 1.31

ey shown is 17.47% which would be correct if it were percolation method. as it’s full immersion - ey should be 21.68% as ey=(tds*total water)/dose which can be checked here https://www.espressoschool.com.au/coffee-calculator/

Please let me know if you need more data points.

**Comment by graphefruit** [comment]
Hello @diskox,
thanks for your report! 
I've fixed this, and this change will be inherit in version 6.

EY will be calculated now with your given formular if given:
prepartion type is style == immersion & brew water > 0 

Thanks again & Have a great weekend
Lars
