### ISSUE TITLE
fix lunar scale bugs

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#266]

**Comment by graphefruit** [comment]
https://github.com/don/cordova-plugin-ble-central/issues/828 - Add workaround like described

**Comment by graphefruit** [comment]
Auto connect on Lunar scale not working / shuting down lunar, crashes iOS app

**Comment by graphefruit** [comment]
![image](https://user-images.githubusercontent.com/6260244/142758675-980b3326-1dbc-43c1-9a97-2f6b6ac1018f.png)
It looks like the app makes an "getData" don't know exactly from where, and the app crashes because he doesn't know a uuid

![image](https://user-images.githubusercontent.com/6260244/142758774-dcc7d00f-45ba-40fc-b67e-393a992763f7.png)


So it looks like the retrieved service uuid is wrong, but I don't understand this properly

**Comment by graphefruit** [comment]
Ok... i thought it would help onto the constructor to add:
`  if (this.device_id && this.weight_uuid && this.rx_char_uuid) {`

But it still crashes, so it looks like a much more deeper problem

**Comment by mike1808** [comment]
@graphefruit when does it happen? After which step in the app it crashes? Can you back trace to exact ble central call from your app?

**Comment by graphefruit** [comment]
@mike1808, after he connects the scale via settings, the app crashes.

So he cant even brew and receive weight data or something like this.
App also crashes when trying to auto connect.

Fun fact: Multivitaminjuice's lunar-scale doesn't has this issue - I fixed yesterday with him, the autoconnect issues.

I have a pair coding later again with him, maybe I can reproduce something.

I don't have more information, just the crash report via the testflight report :(
For me it references that one uuid is not right/existing, thats why I tried to not attach to notifications if one value is not set in typescript

**Comment by graphefruit** [comment]
> Can you back trace to exact ble central call from your app?

Sadly no :(

**Comment by graphefruit** [comment]
Some more points:

It comes from stopNotification

```
// stopNotification: function (device_id, service_uuid, characteristic_uuid, success, failure) {
- (void)stopNotification:(CDVInvokedUrlCommand*)command {
    NSLog(@"stop notification");

    BLECommandContext *context = [self getData:command prop:CBCharacteristicPropertyNotify];
```
Then he tries to getData

```
// expecting deviceUUID, serviceUUID, characteristicUUID in command.arguments
-(BLECommandContext*) getData:(CDVInvokedUrlCommand*)command prop:(CBCharacteristicProperties)prop {
    NSLog(@"getData");

    CDVPluginResult *pluginResult = nil;

    NSString *deviceUUIDString = [command argumentAtIndex:0];
    NSString *serviceUUIDString = [command argumentAtIndex:1];
    NSString *characteristicUUIDString = [command argumentAtIndex:2];

    CBUUID *serviceUUID = [CBUUID UUIDWithString:serviceUUIDString];
```

And there he tries to get the serviceUUID and crashes.

More information is not given

**Comment by graphefruit** [comment]
We found the issue, thanks to MultivitaminJuice.
Looks like its an issue cause of the merge to support the pyxs scale.
Log will come soon

**Comment by graphefruit** [comment]
@mike1808 
I could fix the issues with MultivitaminJuice.
First of all: I made a complete rollback of your pyxis support, it didn't work.
Even after making many changes to be as near as possible on the old code, it didn't work :(

You find attached three logs with step by step:
[finddevices.log](https://github.com/graphefruit/Beanconqueror/files/7577013/finddevices.log)
[findScale.log](https://github.com/graphefruit/Beanconqueror/files/7577012/findScale.log)
[FindScaleAndConnect.log](https://github.com/graphefruit/Beanconqueror/files/7577011/FindScaleAndConnect.log)

First we just found the devices, second we tried to find the scale, and third we found everything and just connect to bluetooth, without buildung the acaia-class.

When connecting the acaia class, following happend:
[Error.log](https://github.com/graphefruit/Beanconqueror/files/7577019/Error.log)


We've encountered the issue, that the app crashes, when the smart scale disconnected.
This was due the code on `disconnect()`
`await promisify(ble.stopNotification)((this.device_id, this.weight_uuid, this.char_uuid));`
-> This made the crashlog I posted above.
The scale was already disconnected by the BLE-Class, and the code still tries to stop the notification, and then the native code crashed.


Pyxis scale:
It looks like this is a bigger topic to be honest.
One thing I saw is that the function `to128bitUUID` just uses the lunar characteristics, not the pyxis characteristics

Have a great evening

**Comment by graphefruit** [comment]
Oh and one error occuring often:
```
2021-11-21 19:57:33.036182+0100 Beanconqueror[1619:227614] getData
2021-11-21 19:57:33.036584+0100 Beanconqueror[1619:227614] Looking for 2A80 with properties 8
2021-11-21 19:57:33.036775+0100 Beanconqueror[1619:227614] Looking for 2A80
2021-11-21 19:57:33.038300+0100 Beanconqueror[1619:227614] Error Domain=CBATTErrorDomain Code=3 "Writing is not permitted." UserInfo={NSLocalizedDescription=Writing is not permitted.}
2021-11-21 19:57:33.041698+0100 Beanconqueror[1619:227614] ERROR: ACAIA ERROR: ["failed to write to characteristic, but we are ignoring it","Writing is not permitted.",false]
```

**Comment by graphefruit** [comment]
#276  - I gonna close this one, and reference.
