### ISSUE TITLE
Bug: scales are not connected on add brew page

### ISSUE THREAD

**Issue by mike1808** [graphefruit/Beanconqueror#281]
If you set scales auto connect and the "Add Brew" page as the first page of the app it doesn't automatically connects to the scale. You have to go back to brews page and wait.

Reproduction steps:
1. Setup Bluetooth scales with auto connect
2. Set your first app page to add brew
3. Close the app
4. Open the app

Expected result: scales are connected when app is opened

Actual result: scales are not connected.

**Comment by graphefruit** [comment]
Hi @mike1808,
I'll test this out again.
I had no issues with my decent here to be honest. 

You did set the settings to not loose connection right?

**Comment by graphefruit** [comment]
Hi @mike1808 
Found the issue and fixed it ;)
