### ISSUE TITLE
Bug: Excel export - Beans sheet not aligned properly with multiple beans

### ISSUE THREAD

**Issue by christophedc0** [graphefruit/Beanconqueror#283]
Hi,

I've noticed that on the iOS version, when I use excel export, the beans section is misaligned when there are multiple beans.

currently:
| 2. Country | 2. Region | 2. Farm | 2. Farmer | 2. Elevation | 2. Variety | 2. Processing | 2. Harvested | 2. Percentage | 2. Bean certification |
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Peru | El Palto |   |   | 1250-1500 | Typica, Catimor, Catuai | Washed, Organic |  

While every 'second' value should be shifted one column to the left.

what it should be:

| 2. Country | 2. Region | 2. Farm | 2. Farmer | 2. Elevation | 2. Variety | 2. Processing | 2. Harvested | 2. Percentage | 2. Bean certification |
 -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
  Peru | El Palto |   |   | 1250-1500 | Typica, Catimor, Catuai | Washed, Organic |

**Comment by graphefruit** [comment]
Thanks for reporting @christophedc0, I'll have a look at it

**Comment by graphefruit** [comment]
Hey @christophedc0  - Bug is resolved and will fix will be inherited in next version.
Best regards & Thanks again for reporting
Lars
