### ISSUE TITLE
Translation: Ukrainian

### ISSUE THREAD

**Issue by leits** [graphefruit/Beanconqueror#287]
Hi, @graphefruit!
I want to add Ukrainian translation to Beanconqueror and am ready to support the translation in the future.

I found translation files into `/src/assets/i18n`. what do I need to do other than add a translation file?

**Comment by graphefruit** [comment]
Hey @leits,
you just need to add another translation file with the abbreviation.json.

And the second thing would be to pass me the possible localize-languages for Ukrainian so I can add them when searching.
-> https://github.com/graphefruit/Beanconqueror/blob/master/src/app/app.component.ts#L307

PS: I'm actually on Version 6.1 so there will some more translations on its way.

**Comment by leits** [comment]
Thanks! I'll add a translation this week.

By the way, you can use weblate.org for translation. They offer a free plan for open-source projects, and users on this platform are actively adding new translations by themselves.

**Comment by graphefruit** [comment]
Hello there,
translations now can be done via Lokalise.
If there is interested, please write me an e-mail: info@beanconqueror.com
So I can add you as an translator.

Have a great cup of coffee
Lars
