### ISSUE TITLE
Show weight data live before a brew is started

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#293]
Would it make sense to show the live weight data before a brew is started? Then the app would able to be used without really looking at the scale. When pressing something like the scale button next to the ground coffee entry we would be able to see which number exactly will be placed there before it's entered as well as verify that the scale is tared before starting the timer for example.

**Comment by graphefruit** [comment]
I gonna have a look to attach the scale weight into the information container over the flow-chart

**Comment by mehalter** [comment]
Thanks so much!

**Comment by graphefruit** [comment]
Weight is now shown, even when the timer is not started. 
![img](https://user-images.githubusercontent.com/6260244/148818139-523ee6ee-2b40-4f49-9e80-c2b8bb043e4e.jpeg)
