### ISSUE TITLE
Hosting the App on Google Playstore

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#3]
Advantages are the broad availability to different Androidusers and the collected metrics.
Disadvantages are that we need to keep it up-to-date and that we are depending on Google.
An alternative might be PWA only or uploading through e.g. F-Droid.

**Comment by graphefruit** [comment]
App is hosted on Playstore now.
https://play.google.com/store/apps/details?id=com.beanconqueror.app
