### ISSUE TITLE
Ability to edit date&time of brews?

### ISSUE THREAD

**Issue by simplysaru** [graphefruit/Beanconqueror#302]
Sorry, if I missed this somewhere in the app or in your documentation. 

I was using this app consistently for a while now but looks like I missed tracking a few afternoon brews. I do remember the ratios and date, but now I can't add them to their respective dates. Is there a way to already do this? I'm not seeing an option to edit the dates. Now my beans available is incorrect.

**Comment by graphefruit** [comment]
Hello @simplysaru,
its possible to edit the datetime of the brews.
For this you need to go via the Menu -> Brewing Parameters -> Manage parameters -> Scroll down -> "Custom brewing time"

Activate the checkbox and then you can set your dates of your brews from hand.

If you know any further help, just let me know

**Comment by simplysaru** [comment]
Hi @graphefruit, 

Thanks, didn't dig this deep into the brewing menu parameters menu. 
Please feel free to close the issue.
