### ISSUE TITLE
Feature: use scale to when adding beans

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#312]
When I add beans to Beanconqueror I like to weight them out and it would be nice to have a small tare and get scale weight button similar to the brewing page

**Comment by graphefruit** [comment]
Hey @mehalter,
I'll have a look.
I understand the feature, but I'd guess that 90% of the users buys a bag from the roastery.

I'll include this feature also directly for roasts which roasted-bean weight

**Comment by mehalter** [comment]
Ok cool thank you :) Yeah, I also mostly buy bags from roasteries but find that there is sometimes a decent difference in the weight on the bag and the actual weight once I weigh it because sometimes they overshoot and I end up with more beans than is labelled. (I also might just be anal :p )

**Comment by graphefruit** [comment]
Feature was added, greenbean weight aswell as normal weight (roasted weight on the roasted tab) is supported on scale
