### ISSUE TITLE
Bug: Inconsistent flow rate graph working

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#314]
Ever since the zoom and share functionality has been added I've been getting some weird inconsistencies with the flow graph displaying during the brew. Sometimes it works and sometimes it decides not to, but the weight is being read correctly so I don't think this is an issue with the scale itself. Also if I save and then open the brew the correct flow graph is displayed even if it isn't displayed when the brew is happening.

https://imgur.com/gallery/e6g5cF2

**Comment by graphefruit** [comment]
Hey @mehalter,
uff.
I think this comes from the zooming plugin.
I gonna disable the zoom feature on edit/add page, and just support it on the detail page (this should be enough I think)
Zooming while brewing shouldn't be a good intent at all.

**Comment by graphefruit** [comment]
@mehalter Please try again, I disabled zoom on add/edit page page

**Comment by mehalter** [comment]
I can confirm that I am not getting the unexpected behavior anymore. Looks like disabling the zooming fixed it right up :) thank you!

**Comment by graphefruit** [comment]
Great to see this!
I gonna close the issue so
