### ISSUE TITLE
File Locations

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#317]
When I export my data using the Settings -> Data Transfer -> Export I get a nice `json` that references other files. That I've noticed for both images and flow_profile. I'm wondering where these files are located. For example a `flow_profile` may be marked as `"brews/52e53535-67dc-4c7b-af50-097d583303f5_flow_profile.json"`, but I can't seem to find this `brews/` folder or any `*_flow_profile.json` files on my phone.

**Comment by graphefruit** [comment]
Images aswell as the flow profile data are stored inside the application container.
They cannot be accessed from the file browser system.
Thats why on the export I access the images and save them inside the download folder.
The flow profiles are actually not supported, as export and import.

**Comment by graphefruit** [comment]
I've added the export functionality for the flow profiles on the download folder now.
Import is actually not working

**Comment by graphefruit** [comment]
Going to close this.
Export is working. For import there would be a new feature needed.
