### ISSUE TITLE
Can't add image on Android

### ISSUE THREAD

**Issue by Nailik** [graphefruit/Beanconqueror#318]
Hi,

i try to add an image to my beans on Android 11.

It opens the file chooser but after selecting file it's not being added.

All logs i can see:

```
2022-01-26 22:00:37.276 20346-20475/com.beanconqueror.app D/[FilePath plugin]:: Filepath: /storage/emulated/0/Download/Foto1.jpg
2022-01-26 22:00:37.276 20346-20475/com.beanconqueror.app W/PluginManager: THREAD WARNING: exec() call to FilePath.resolveNativePath blocked the main thread for 26ms. Plugin should use CordovaInterface.getThreadPool().
2022-01-26 22:00:37.554 20346-20346/com.beanconqueror.app I/chromium: [INFO:CONSOLE(1)] "ERROR Error: Uncaught (in promise): [object Undefined]", source: http://localhost/main-es2020.5ceff1f2fae2e421fcf1.js (1)
```

**Comment by graphefruit** [comment]
Hi @Nailik,
is the storage/emulated maybe a SD-Card slot?
Cordova has an issue with specific paths (one is SD-Card sadly)

**Comment by graphefruit** [comment]
Please try adding images from different path-locations (gallery, download, etc) and have a look if this is also not working on your side please.

Also please check if you can add images from your camera, or if this is not working aswell

**Comment by Nailik** [comment]
I have no SD-Card in my device.

Using a Mi Mix 2 with lineage os - it worked previously.

I tried adding from normal camera path and i copied to download path, both didn't work.

Choosing "record" doesn't open the camera
`
2022-01-26 22:08:09.641 20346-20475/com.beanconqueror.app D/CameraLauncher: Error: You don't have a default camera.  Your device may not be CTS complaint.`

**Comment by Nailik** [comment]
Probably related to https://github.com/apache/cordova-plugin-camera/issues/673 but should have been fixed with https://github.com/apache/cordova-plugin-camera/pull/684

**Comment by graphefruit** [comment]
Uff, I didn't update anything in the camera section.

Actually I cant update to the latest camera version, because of building issues with cordova.
Need cordova android 11 first sadly.

But the camera plugin doesn't have anything todo with image choosing, these are 2 different workflows

**Comment by graphefruit** [comment]
The difference on the camera path is that 5.4 had 5.0.2, and 6.0 has 5.0.1 (ok, but this shouldn't be the hard issue in the end).

The other plugins were not changed (filepaths etc).

If you want to (and have no problems with may image loss) do a backup of your json-files, and try to install the 5.4 release and have a look if it will work there, so maybe I can grab deeper then

**Comment by Nailik** [comment]
I'll check that tomorrow. 
Did you ever think about using another framework (i know that wouldn't be easy, just curious why you choose cordova)? 
Looks like cordova makes some issues like this and having issues with external paths etc.
Btw thanks for the very fast replies.

**Comment by graphefruit** [comment]
I've developed with cordova before, therefore I was confident in choosing it.
Also I like crossplattform development. (Having 2 code bases is not my thing)

The codebase started on 2017, therefore its already a longer time in the end and new frameworks came up by time

**Comment by graphefruit** [comment]
I've updated the file plugin of another fork maybe it could be a solution of your issue.

The camera is not fixed with this

**Comment by graphefruit** [comment]
I made it to update to the latest camera-plugin, it may fix your issue so.
I'll add a new beta version in the next few days.
But please do a saftey backup, it can result into data loss if you want to try out

**Comment by curio77** [comment]
Have the same or similar issue on my Google Pixel 3 (Android 12): Selecting an image (tried different locations; device has no SD card) briefly shows a progress throbber but otherwise has no apparent effect. Selecting to capture a photo does nothing whatsoever.

**Comment by graphefruit** [comment]
I'm going to close this after I  managed to repeat this situation on my phone and could fix it.
If there is still issues in the next version please reopen a new ticket.
Thanks
Lars
