### ISSUE TITLE
Enhancement: Add a realtime graph

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#319]

**Comment by graphefruit** [comment]
@mike1808  
I've made the first sample for the realtime graph :)

**Comment by mehalter** [comment]
Ever since that latest commit `adb03fc` I've not been able to view the graph during the brew. The scale and the time progress (i.e. the graph is expanding) but the lines are never being plotted.

**Comment by graphefruit** [comment]
It's a bit broken actually I saw that today.
Start a brew then reset to zero then connect scale and it should work.

Also the pause system needs to get fixed.
I need to play with Unix timestamps that all of this is working :/

**Comment by graphefruit** [comment]
One more issue is (what just came up to my mind):
If you wait actually to long to start, the delay already faded, thats why nothing is visible

**Comment by graphefruit** [comment]
@mehalter should work now more reliable

**Comment by graphefruit** [comment]
After I've heard no more issues here, I'd going to close this issue
