### ISSUE TITLE
enhancement: show rate dialog when archiving beans

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#326]
When a bean is finished, the app asks if you want to archive the bean and shows a dialog to rate the bean:

![image](https://user-images.githubusercontent.com/431045/156321742-72959a4d-9fb0-405a-96e7-38e9855e722b.png)

However, if you select archiving from the list of beans, you don't get this dialog. 
I propose to have this dialog in the archive action from the bean list as well, to rate the beans quickly there as well.

**Comment by graphefruit** [comment]
Thanks for proposing.
added.
