### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by papaGregor** [graphefruit/Beanconqueror#329]
Adding a bean → Blend → “Unknown” is misspelled as “Unkown”

![4A46A98D-6A00-4A02-A6C0-88BFB226387A](https://user-images.githubusercontent.com/17756141/155398482-e352cfc8-5315-485a-9d6b-5aaed859af64.png)

**Comment by graphefruit** [comment]
Thanks for reporting, this is fixed in version 6.1
