### ISSUE TITLE
Health app: Caffeine: edits & deletions not registered

### ISSUE THREAD

**Issue by papaGregor** [graphefruit/Beanconqueror#330]
After the user adds a brew, if that brew’s ground coffee amount is altered, the change is not reflected in the Health app data. Likewise, if the brew is deleted, the caffeine data entry is not deleted in Health.

**Comment by graphefruit** [comment]
Hey @papaGregor,
thanks for reporting.
Sadly this is not easy possible.
iHealth doesn't pass a unique id back which I could edit.
I just can delete a range of data sets in a specific time.

I could add this possibility.
But when the time will be edited on a brew, and after that edited/deleted, the issue will still be available

**Comment by graphefruit** [comment]
This ticket is pretty old, and there was no questions regarding this feature by the community.
I'll close this one as not planned right now.
If needed, please open up a new one.
Have a great cup of coffee
Lars
