### ISSUE TITLE
empty bean view

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#337]
With the latest code on the `develop` branch my list of beans has become empty both active and archived. I think it has something to do with the filter (complete guess). I can still make new brews using the current beans added so I'm sure the data is there.

@graphefruit

**Comment by graphefruit** [comment]
Hey @mehalter,
goto the settings page, change your brew rating range +1 and change it back.
It will reset your filter and everything should work as intended.

When rolling out, I'll run an update script (uiUpdate-Service) which will fix this on every user on the first startup of the new verison.

**Comment by mehalter** [comment]
Awesome! Worked like a charm :)
