### ISSUE TITLE
Lunar 2021 Connectivity Issue

### ISSUE THREAD

**Issue by twilight-coffee** [graphefruit/Beanconqueror#338]
every so often (maybe 40% of the time) the scale connects (app shows the banner, scale shows the connection icon) but no data seems to transfer between my iPhone and the scale. weight is not transmitted, and actions from the app such as Tare or the button that sets bean weight from scale do not seem to do anything either.

A force close of the app has fixed it 99% of the time, and the remaining 1% requires a second force close of the app.

**Comment by graphefruit** [comment]
Hey @twilight-coffee thanks for reporting here.
Tricky thing, you're the first Lunar 2021 owner which has this issue :O
Did you updated your iOS to the latest version, aswell has patched lunar to the latest release?

**Comment by graphefruit** [comment]
He @twilight-coffee did you had the chance to test with the latest version 6.1? 
Is this still a case here?

**Comment by graphefruit** [comment]
This case can't be improved anymore, so I going to close this ticket.
Specially on iOS this is more common, on Android it works like 99% of the time.
Make sure the weight-tile is live updated on the brew add/edit page, if not, please reconnect the scale in the menu "...", until the weight-tile is updated with the current weight displayed on the scale and you hear a beep in best case.

For everything else, please open up a ticket at Acaia to provide open API access.
Thanks for your understanding & support
Lars
