### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#34]
Is there an English version?

**Comment by graphefruit** [comment]
Not yet. Is this actually an asked question? Never heard of this before

**Comment by DeastinY** [comment]
Surprisingly yes :)
do you know if it's hard to pull off? I'd be willing to do the translations, but not sure how to implement it best

**Comment by graphefruit** [comment]
I gonna have a look, shouldn't be that hard. There are good translation plugins.

**Comment by graphefruit** [comment]
Translation service is now ready  to be filled.
Second step will be to get the device language and to fill this.
I'll support english/german in first steps - rest would need to  be added from community

**Comment by graphefruit** [comment]
Merged and finished.
