### ISSUE TITLE
Grinders -> Grams grinded

### ISSUE THREAD

**Issue by diskox** [graphefruit/Beanconqueror#347]
grinded -> ground

[https://writingexplained.org/grinded-or-ground
](https://writingexplained.org/grinded-or-ground
)

Ground is the correct past tense form.
Grinded is an improper conjugation, unless the reference is to dancing.

**Comment by graphefruit** [comment]
Hey @diskox 
Thanks for reporting!
Fixed :)
Greetings
Lars
