### ISSUE TITLE
Data loss with Version 6.1 - Android

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#355]
You find all information here: https://beanconqueror.com/faq

**Comment by rmnwnsx** [comment]
Hi, I haven't find anything but accidental Export in the Folder. I have Android 12, Pixel 4A (5G)
![Screenshot_20220427-131728](https://user-images.githubusercontent.com/47259322/165507010-bdf710f6-643d-4c4b-a721-d55276a7d8de.png)

**Comment by graphefruit** [comment]
Hey @rmnwnsx,
Sorry to hear this :(, if there is no file at all, we'll have a rough time.
I just have one thought, which I didn't try out at all:

You maybe could try to force install this version from Github: https://github.com/graphefruit/Beanconqueror/releases/tag/v.6.0.0
The important thing is that you don't remove the app, you'd need to over install it.

As reference: https://stackoverflow.com/questions/13400499/is-there-any-way-to-ignore-install-failed-version-downgrade-on-application-insta

Maybe this will get you back the database because its another APK-File, there you could export all needed files, and then upgrade + import.

**Comment by graphefruit** [comment]
I've made the latest tests.
Downloading the 6.0.0 version and installing it via ADB
```
adb install -t -r -d /pathtoapk.apk
```
Will overwrite the actual installation from Play Store and you'll see all your data.

Please go into the settings menu, press export.
You'll find then on the `/Download/Beanconqueror_export/` all needed data.

Go again into the Play Store, and update the app, then go to the settings menu, press import and choose the .JSON-File from `/Download/Beanconqueror_export/` to reimport

**Comment by jjsil** [comment]
I can confirm that sideloading v6.0.0 with adb worked to restore the data! Which is great because I didn't have auto exports in the Downloads folder either 😅
Thanks for the workaround @graphefruit!

**Comment by graphefruit** [comment]
@jjsil Great to hear this! Thanks for sharing!

**Comment by SachaMartinezCastillo** [comment]
Just try it and it works, I did an export in the 6.1 and wasn't sure if was going to work because of that but didn't matter. I was able to get all the data again. Thanks!

**Comment by Dvvarf** [comment]
On my device too the Beanconqueror_export folder was empty.
However, I was not able to sideload an application.
* I've downloaded the one from https://github.com/graphefruit/Beanconqueror/releases/tag/v.6.0.0
* Enabled dev mode on my device, connected it to PC (Windows 10) and allowed the connection.
> D:\platform-tools>adb devices
List of devices attached
5200b6c0eaa1456f        device
* However, installation fails:
> D:\platform-tools>adb install -t -r -d bean.apk
Performing Streamed Install
adb: failed to install bean.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

Does anyone has any idea how to force the installation? Will I have to build the application manually with version being spoofed? Also, is the version in releases is the debug version? Downgrading will not work with release version of the package.

> D:\platform-tools>adb --version
Android Debug Bridge version 1.0.41
Version 33.0.2-8557947
Installed as D:\platform-tools\adb.exe

**Comment by graphefruit** [comment]
Hello @Dvvarf ,
sorry to hear this.
For this case there is a lost option:

After ADB doesn't work for you, I built the old version, with a new android-version number:  https://github.com/graphefruit/Beanconqueror/releases/tag/vDontUse

Please install this version over the actual application.
After you successfully exported, check your Beanconqueror_export folder, and do even a backup.
After that you need to uninstall and reinstall from the Android Store (because the Rollback Version number is higher then the real one) and importing.
Important too: If you have connected your bluetooth scale and did shots with it, the flow-rawdata won't be imported again, so they will be lost - but I think thats a small tradeoff, because you still have the exported once at least.

Let me know if this helped
Lars

**Comment by graphefruit** [comment]
After this issue is now open for about one year, I close it, after I haven't heard any more of this.
Thanks for your support and your helps and your understandings!
