### ISSUE TITLE
Weird brew time values?

### ISSUE THREAD

**Issue by DustVoice** [graphefruit/Beanconqueror#386]
So I finally switched from Smart Espresso Profiler to Beanconqueror full time.
As I used to do with all my SE Profiler data, I use a python script to visualize all the exported data, compare different brews to one another, etc., in other words, I'm using the brew time values for my x-axis and the weight & flowrate values for my y-axis respectively.
The .xlsx sheets are a godsent compared to CSV, but I encountered one major issue, at least for me.

The brew time has ".10" at the end of some numbers. I noticed, that the brew time sometimes extends to ".10". For example, a series of brew time values would be: [24.1, 24.2, 24.3, 24.4, 24.5, 24.6, 24.7, 24.8, 24.9, 24.10].
This of course completely confuses the data converter as it thinks "24.1"  and "24.10" are the same numbers, which in theory they are.
Is this intended behavior? How should I approach converting the brew time values for usage as my x-axis for my graphs?

Thanks in advance, unfortunately, I didn't find exhaustive documentation for the .xlsx sheets (understanding the different columns actual/old weight, etc. of the sheet is confusing enough 😅) which is why I hope, I'm asking this question in the right place.

**Comment by graphefruit** [comment]
Hi @DustVoice,
actually the .1,.2,.3 are the ticks from the scale.
I've had the problem that I needed to calculate all send values from the scale within one second, and the issue is/was, that sometimes I get 4 values, sometimes 10.
After I calculate the water flow within 1 sec I needed to remember them.

Also I've had issues with displaying the graph correctly, and with the tick solution it worked so far, maybe in the near future a new / better solution can be found, i'm not 100% perfect in drawing those graphs.


I just had a look into the code, can't you use the timestamp (unix?) and go on from there? 

Greetings
Lars

**Comment by DustVoice** [comment]
Hi @graphefruit,
I understand the problem here.
The reason why I didn't use the timestamps previously was that there are multiple values for each timestamp. But I now understand why.

I will look into it a little bit further and determine whether it is feasible for me to calculate the distribution of the values between one timestamp and another myself or not.
Currently, I'm modifying the .10 to be a .95, which doesn't produce the most accurate graph, but it at least worked. 

I will think about this issue some more to maybe come up with a better solution, but we'll see.
Thanks for your fast response, and have a nice day.

David

**Comment by DustVoice** [comment]
Oooooh, you know what? I just opened up the new datasheet from today. And guess what? The timestamp values are not all the same for multiple values.
It turns out I activated the "Ignore anomaly values" options, which completely screwed over my flowrate values and the timestamps. Without this option, the timestamps should be sufficient for everything I need, so I'm going to close this non-issue.
Thanks for your great work!

**Comment by graphefruit** [comment]
Great to hear.
Ignore anomaly really waits one second and then puts all together.
I'll have a look if i still could write a better "timestamp", maybe I'm also not writing the perfect timings here.

I searched for multiple graph solutions and the actual solution is the only one which worked "good", after its not native, its good and bad at the same time.
If you have any more suggestions, just open another ticket please, I try to help as good as possible

**Comment by graphefruit** [comment]
@DustVoice Found the issue with the anomaly, i just took one unix-timestamp after i fired all value at once, I save now the timestamp at start, and even with the 1 sec delay the right timestamp will be saved.

**Comment by DustVoice** [comment]
Nice thanks for all your work. It really is astonishing what you created and that the project is that well maintained. I'm looking forward to contributing as soon as I find some time. The anomaly option didn't really benefit me anyway as I'm just pulling normal espresso shots, so until I do some V60 etc. I will just leave it off. But thanks anyways for the fix
