### ISSUE TITLE
Auto start shot using pressure threshold

### ISSUE THREAD

**Issue by wannabecoffeenerd** [graphefruit/Beanconqueror#387]
Add ability to auto start a shot when you have a pressure transducer by setting a pressure threshold. Say, you set that as 0.5 bar, then the shot and graphs would automatically start when the pressure exceeds 0.5 bar. And that value could be configurable

**Comment by graphefruit** [comment]
Hey @wannabecoffeenerd 
This is included, I forgot to link the ticket.
