### ISSUE TITLE
Not Able to input decimal separator

### ISSUE THREAD

**Issue by wulfithewulf** [graphefruit/Beanconqueror#4]
Hello,

I am not able to enter the decimal separator in the Input fields for masses, temperature and times.

[screenshot LG G5](https://user-images.githubusercontent.com/27869395/41312670-f3bc1a50-6e87-11e8-98ea-956d6c8f21a6.jpg)  
  
I have a LG G5 Smartphone with stock Android installed.

Thanks.

**Comment by graphefruit** [comment]
I'll have a look on it, looks like G5 behaves different then my Pixel 2

**Comment by wulfithewulf** [comment]
yeah thats nice, if you want me to install a test apk or something just contact me.

**Comment by graphefruit** [comment]
Fixed with release: https://github.com/graphefruit/Beanconqueror/releases/tag/v1.1.0
Can you please test?

**Comment by wulfithewulf** [comment]
Yeah it works! However I detected some inconsistencies in the time fields. The one with the start button has the numeric input the other two the normal text input. But this is not important to me since it is not measuring seconds with decimals, so are not necessary to have text inputs, I guess.

**Comment by graphefruit** [comment]
Yes, maybe I'm gonna add a litte feature and adding milliseconds ;)
So I'm gonna close this one.
If you got any new issues / feature requests don't hassle to open a new ticket :) thanks
