### ISSUE TITLE
Making bluetooth devices code as a new repo for more developers under the MIT-Licence

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#405]
Hey together,
I'd like to migrate the code for all bluetooth devices into a new repository so other developers can integrate them by demand.
I'd like to change the licence with this: MIT
I've made first tests and it looks working :)

Could you please comment here if this would be ok for you?  
@mehalter @mike1808 @silasg @https://github.com/Mimoja @hermanmak 

If this would not be ok, I'd make it as GPLv3

Thanks!
Lars

**Comment by mehalter** [comment]
Sounds good to me @graphefruit !

**Comment by mike1808** [comment]
Sounds good. You can add this to the end of the commit to make it a commit with multiple authors

```
Co-authored-by: name <name@example.com>
```

**Comment by silasg** [comment]
Of course ok for me, too :) I don't remember the Beanconqueror integration well but AFAIR the API was relatively use case specific. While playing around with the Jimmy scale I created https://github.com/silasg/jimmy-js as a View.js app running in chrome inspired by one of @Mimoja s projects. That was easier to debug than building a Ionic app.

If you want, you can also integrate some of the advanced features from https://github.com/silasg/jimmy-js/blob/main/src/jimmy.ts that I didn't need for Beanconqueror.

**Comment by Mimoja** [comment]
Hey Ho, let's go MIT

-Mimoja 2022 <git@mimoja.de>

**Comment by hermanmak** [comment]
sounds good! I'll have some time in a week or two!!

**Comment by graphefruit** [comment]
@hermanmak Thanks! You don'T need to do something, I'll migrate ;)

**Comment by graphefruit** [comment]
Won't be done in the near future, code is back, but a bit changed/tweaked
