### ISSUE TITLE
Add water recipes 

### ISSUE THREAD

**Issue by lmclister** [graphefruit/Beanconqueror#414]
Water makes a huge difference in taste. It would be good to add information to a brew
https://www.baristahustle.com/blog/diy-water-recipes-redux/

**Comment by lmclister** [comment]
I dug deep into the settings and found it. It would be awesome if it appeared on the brew card

**Comment by graphefruit** [comment]
> I dug deep into the settings and found it. It would be awesome if it appeared on the brew card

Hey @lmclister, sorry for the late response.
You found the first step -> Activate in settings -> A new menu will appear "Water" where you can add your water then.

If you want the water appearing on the brew card, please make sure to go to "Brewing parameters" -> "List view parameters" -> And activate water.
That will show you the water parameter in the brew card.

Please care: If you customized your preparation methods, you need to activate it there aswell
