### ISSUE TITLE
Import mechanism is not working, due to Bug on file-plugin (android) 

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#417]

**Comment by ediblemanager** [comment]
Hi @graphefruit ,

Any updates on importing? Currently got a blank app, and hungry for a brew ☕️!

**Comment by graphefruit** [comment]
Hey @ediblemanager,
like written on another stream: Please install Version 6.1 from Github, import and then update via Playstore.
Make sure that the actual paths are right :)

The PR is here: https://github.com/apache/cordova-plugin-file/issues/525 but not released, it looks like I need to adapt to the hotfix-branch so long.

**Comment by graphefruit** [comment]
Actually this bug is fixed with 6.3, but with an overwrite of the plugin, I'll let this ticket open here.

**Comment by graphefruit** [comment]
After updating to ionic 7, all plugins working as intended now. Closing this
