### ISSUE TITLE
Hiroia Jimmy disconnects exactly every 10s

### ISSUE THREAD

**Issue by kacase** [graphefruit/Beanconqueror#418]
I'm running Beanconqueror 6.2 on an iPad Pro and iPhone Pro both running v16.

I am also using a Hiroia Jimmy with the latest firmware update (2.0.4).

Connecting to the app works very well, however the scale disconnects exactly every 10seconds for an unknown reason.

![image](https://user-images.githubusercontent.com/847267/199943170-1ba7f679-a7ad-45a9-a543-a48d13c48100.jpeg)

![image](https://user-images.githubusercontent.com/847267/199944043-b32597a8-2e38-4458-954e-f0c1acf7d575.jpeg)

**Comment by graphefruit** [comment]
@silasg 
Could you please try if you got the same issue?

**Comment by kacase** [comment]
I did activate the logging setting for scales, but was not able to locate the logfile.

**Comment by graphefruit** [comment]
Hey @kacase,
the logs can be found via "About Beanconqueror" -> "Logs" -> You can send the logs as .JSON.
But I don't think there will be a lot of information given because of the disconnect.

I maybe could think that with the new hiroia firmware, the scale maybe wants a keep alive ping.
Do you maybe have an android device on your hand to test it with this?

I sadly don't have any Hiroia Scale, so I cant debug nor fix this issue in a good way - specially it worked for a long time

**Comment by kacase** [comment]
Unfortunately I do not have an android device to test on.

**Comment by silasg** [comment]
> @silasg 
> 
> Could you please try if you got the same issue? 

Sure, will do so. But unfortunately I probably need a few days.

**Comment by silasg** [comment]
Today I tried to reproduce the issue. Unfortunately so far I wasn't able to do so. 

What I tried:
Connected the scale and did nothing for a few minutes but checking the scale's BT indicator. It did not turn off. 

Then I brewed a V60 with 2:20 total drawdown time. This also worked well:

![image](https://user-images.githubusercontent.com/275404/200165648-27748c80-d817-4ee7-b32d-707e671f1761.jpeg)

I used an iPhone 13 Pro running iOS 16.1 and Beanconqueror 6.2 from App Store. Scale Firmware is 2.0.4. 

@kacase I'm not sure if I tried correctly. Does the scale automatically reconnect for you? I wonder if I just missed the connection outages because I wasn't pouring at those moments?!

For you have another BT scale to try? Does it behaves differently?

Does Beanconqueror keeps scale connection alive when inactive (see settings)? And keeps it the screen turned on?

Thanks in advance!

**Comment by kacase** [comment]
Hi @silasg,

The scale connection does not only drop during brew, but also in the idle state of the app and consistently after 10s of connection.
The notification "scale disconnected unexpectedly" shows up.

The scale does reconnect automatically after 3-5 seconds. And the app shows the "[scale name] connected" notification

I tested the keep connection alive functionality both on and off. No change in behaviour.

Unfortunately I don't have another bluetooth scale available, but I'll try to find one.

The connection to hiroias app is stable and does not disconnect.

**Comment by silasg** [comment]
Thanks for your quick response @kacase

This sounds like it should have been able to reproduce it. But I only get the "disconnected unexpectedly" message when I turn off the scale while the app is running.

I also tried on my iPad Air as well as an really old and slow Android phone. Connections to both devices where stable. 

Do you use the scale with the display unit attached or detached? I wonder what could make a difference.

**Comment by graphefruit** [comment]
Hi @silasg,
thank you for your support and time! <3 

@kacase Could you go and try to connect the scale, goto "add a new brew" and then continuously press "tare" and see if the scale still keeps disconnecting and reconnecting?

**Comment by kacase** [comment]
> Thanks for your quick response @kacase
> 
> This sounds like it should have been able to reproduce it. But I only get the "disconnected unexpectedly" message when I turn off the scale while the app is running.
> 
> I also tried on my iPad Air as well as a really old and slow Android phone. Connections to both devices where stable.
> 
> Do you use the scale with the display unit attached or detached? I wonder what could make a difference.

I did try with both attached and detatched display. With the same results.
On both an iPhone 12 Pro Max runing iOs 16.1 as well as an iPad Pro M1 running iOS 16.1 as well. 
Battery saver mode was disabled on both devices.


In the Hiroia Smart Scale App, I am getting a consistent connection without drop-outs.

**Comment by kacase** [comment]
I ran a factory reset on my Hiroia Jimmy and it now seems to work fine with the iPhone.

I am still not sure what the issue was, but It seems like it was somehow related to the config of my hiroia and how it interacted with beanconqueror
Albeit there was nothing specifically configured.

Two more notes:

- whenever I press connect in Settings > Bluetoooth Scale for the first time after starting the app, I get a warning: "bluetooth not activated, please activate to work properly".
- I am for some reason still not able to connect the scale on my iPad. Now it is not found at all.

**Comment by graphefruit** [comment]
> I ran a factory reset on my Hiroia Jimmy and it now seems to work fine with the iPhone.
Good and bad at once :(

> @kacase Could you go and try to connect the scale, goto "add a new brew" and then continuously press "tare" and see if the scale still keeps disconnecting and reconnecting?
With this test it would be possible to check if the scale would need a "keep-alive" ping to not disconnect (which is build in in some other scale variants out of the market)

> * whenever I press connect in Settings > Bluetoooth Scale for the first time after starting the app, I get a warning: "bluetooth not activated, please activate to work properly".
I can't do much for this. Its a plugin that checks if you have enabled bluetooth, I've heard, even if its enabled its a saftey-feature - if you press again (or sometimes later) it should work then without an issue?

> * I am for some reason still not able to connect the scale on my iPad. Now it is not found at all.
Funny thing, I just heard another issue, where an Android device couldn't find another scale aswell - with a different device it worked.
Beanconqueror just listens 60 seconds and tries to search the different scale types.
All found devices are logged (if you enable the logging for bluetooth) - If its possible and you can reproduce this issue, please enable the logs, search and after that send me the logs from the working phone as well from the iPad.
Why it was found before the factory reset is also a huge mystery so.

**Comment by silasg** [comment]
@kacase glad that at least now it seems to work. 

I have the same "turn on Bluetooth" thing. I guess it's expected plug-in behavior?

Regarding the iPad: did you disconnect the scale from your phone before trying? AFAIR the scale isn't discoverable as soon as it's connected to another device.

**Comment by kacase** [comment]
> @kacase glad that at least now it seems to work. 
> 
> I have the same "turn on Bluetooth" thing. I guess it's expected plug-in behavior?
> 
> Regarding the iPad: did you disconnect the scale from your phone before trying? AFAIR the scale isn't discoverable as soon as it's connected to another device. 

Yes. I did disconnect and even turned off bluetooth on the other device.

As far as I know, the Hiroia only has an active connection while the bluetooth symbol is lit up.

**Comment by kacase** [comment]
@graphefruit 

> @kacase Could you go and try to connect the scale, goto "add a new brew" and then continuously press "tare" and see
if the scale still keeps disconnecting and reconnecting?
With this test it would be possible to check if the scale would need a "keep-alive" ping to not disconnect (which is build in in some other scale variants out of the market)

Since the factory reset I am not able to connect at all, so I unfortunately can't run this test.


I sent you the logfiles for both devices via mail.

**Comment by kacase** [comment]
I have found a workaround.

Downloading the official [Hiroia Smart Scale](https://apps.apple.com/app/id1616596477) and connecting the scale once will solve the issue.

The scale is now found and permanently connected.

I suggest adding the following two points to the FAQ for connecting a Hiroia Jimmy

* If the Hiroia Jimmy can't be detected, download the official [Hiroia Smart Scale](https://apps.apple.com/app/id1616596477) app and use it to connect to the scale once. After that you should be able to connect using Beanconqueror.
* If you experience timeouts or frequent disconnects of your Hiroia Jimmy smart scale, use the [Hiroia Smart Scale](https://apps.apple.com/app/id1616596477) app to do a full factory reset and reconnect the scale afterwards.
