### ISSUE TITLE
Npm Package for Bean Sharing

### ISSUE THREAD

**Issue by kacase** [graphefruit/Beanconqueror#419]
We are currently working on the website for a coffee roastery and think it would be amazing to be able to offer Beanconqueror Links directly on this site.

This would allow customers to add their beans directly after purchase and add an additional interface apart from the QR.

While QR offers a great solution for many use-cases, having a solely digital interface would be a neater solution for highly customised offers and just-in-time roasting.

The idea is to offer a minimal NPM/YARN package that allows the generation of valid Beanconqueror links directly and offers typing support to ensure all required attributes are present.

**Comment by graphefruit** [comment]
Hey @kacase,
thanks for the request.
Theres already the possibility for each roastery to create links and put it on the website, so that user can import the beans without qr-code.
Have a sample look here: https://onoma.coffee/shop/kaffee/10-oluf-samson.html

This feature for roasteries is actually pro-bono with no charge of costs.
Otherwise a share-bean mechanism is given with the actual 6.2 version for Beanconqueror User to Beanconqueror user.

Best regards
Lars

**Comment by kacase** [comment]
Hi Lars,

Thanks for the quick response!

This would however require to generate a QR (the link seems to contain a QR Id param) ahead of time, right?

For the highly individual and not-known-ahead types of coffee we might be offering I am not sure how that would work.

E.g. customers of the roastery can create their own blends and give them names, so we only know the parameters for the beans at the time the link should be shown.
Also the link would likely never be reused, as each sale is super individual.

**Comment by graphefruit** [comment]
> E.g. customers of the roastery can create their own blends and give them names, so we only know the parameters for the beans at the time the link should be shown.
> Also the link would likely never be reused, as each sale is super individual.

I don't get the intention right here to be honest.
A user comes to your roastery, blend their own beans - which you roasted - , set a name like "super blend 202" and you want to generate a beanconqueror-link which inherits all the bean information like price, weight, name, variety information and so on? 
So all in all, someone needs to type in all the information when a link shall be generated.

You are right that a QR-Code would need to be created ahead of time, but in future cases their could also be an API which could be requested to full fill the data and create a bean which can be imported.

If this is so customized, is the coffee lover already a Beanconqueror user, or would you go and explain the app aswell?

**Comment by kacase** [comment]
In the roastery we can do small-batch on-demand roasting.

1. The customer walks into the store, and can signs into our web app
2. there they can choose from a very wide variety of green beans and roast profiles
3. Once they confirm a timer is shown when the coffee will be ready and the roasting process is started manually
4. Once done the coffee is bagged, labelled and brought to the customer

A fully custom name such as “super blend 202” is one of the features we are evaluating.

At 3. we already know all the meta-data of the coffee, which due to the sheer variety can’t be known ahead of time. The customer will already be on their mobile device, so It would be an ideal point in time to direct them to beanconqueror and pre-fill all the data.

Quite a few of the customers might never have heard about the app before; but we are big fans of it and think it can be of great benefit for any specialty coffee enthusiast — our main target group.

**Comment by kacase** [comment]
That sounds reasonable then!

In that case I think an NPM Package would be a bit of an overkill, as long as the API is documented adequately.

Is there something I could help with? I'd be happy to start working on the endpoint and create a PR for you to review.

**Comment by graphefruit** [comment]
Hey @kacase,
sorry for the late reply.
Many things ongoing actually.
Inside the code you can find how the beans are shared actually: 
https://github.com/graphefruit/Beanconqueror/blob/1147e4bcc4c10ac6f66d99fa415dceb7560d9247/src/services/shareService/share-service.service.ts#L48

**Comment by graphefruit** [comment]
@kacase - This ticket has been idle for a long time, is there any interest in this case / did my code lines helped?

**Comment by graphefruit** [comment]
Hello @kacase, 
there are some third-party apps outside which already support a bean import, maybe this would fit you case already?

**Comment by graphefruit** [comment]
This topic has been idle for a long time, I gonna close this one.
