### ISSUE TITLE
Stop timer when hitting save in brew

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#454]
Today I noticed, that the timer on the scale (Decent scale) would continue to run when in a brew you just hit save without previously stopping the timer in the app.
I think the app should send the stop signal to the scale when you simply save the brew - or was this just a glitch?

**Comment by graphefruit** [comment]
Hey @reox,
I've added this change, when saving/aborting a brew, the timer will be stopped.
It may be 2 second delay but I think this will not matter, after the right time will be taking for the brew, and its just that the timer won't run all day long.
Best regards
Lars
