### ISSUE TITLE
Acaia Lunar Brew Mode recognition

### ISSUE THREAD

**Issue by borez** [graphefruit/Beanconqueror#456]
Hi there,

Chanced upon this app and it's been one of the best designed brew apps, kudos to the developers!
Am using an Acaia Lunar (non 2021 version) for espresso, and realised some quirks: 

1) The app doesn't auto-start when using the scale's brew modes, and I have to manually start on the app. Does the scale send over mode values via Bluetooth?

2) When using brew modes, the scale resets the timer + tares values after 30 seconds idle. This also clears any recording on the app.

Not sure if there can be any enhancement via the app? I have attached the brew mode logic for reference.

https://help.acaia.co/hc/en-us/articles/4406955534740-Guide-to-Lunar-2021-Modes

**Comment by graphefruit** [comment]
Hello @borez,
thank you for your kind words, and thank you for the request.

1. The app does not know about the mode which is set inside the Acaia scale.
2. This is sadly a known "issue" with this kind of brew mode

Actually Beanconqueror doesn't have any insights how to retrieve the data from the Acaia scale.
The app can just do an enhancement on this, when receiving official acaia support - sorry for this.

I'll let this ticket open, but can't do anything on it yet.

Best regards
Lars

**Comment by jonschreiber** [comment]
just a +1 that I am loving the app, thank you so much Lars. It would be nifty if the graph auto-started with the Lunar scale (in the mode to detect the first drips of espresso) also auto-started to sync the shot timers.

**Comment by graphefruit** [comment]
Hey @borez, Hey @jonschreiber,
Actually I've implemented my own auto-start logic.
You'll get a new button inside the Beanconqueror-App, when this pressed, the App is listening for weight change, and when it recieves a new (higher) weight, the timer starts and starts the timer on the scale aswell, and starting to record the graph.

Therefore Beanconqueror, won't reference to a mode of an acaia, but the benefit is, that it will work with all scales.

Best
Lars

**Comment by graphefruit** [comment]
Reference #608
