### ISSUE TITLE
Feature: auto-completion for further bean parameter text fields

### ISSUE THREAD

**Issue by jon-jm** [graphefruit/Beanconqueror#463]
Would it be possible extend the availability of auto-completion from only roastery to
– county of origin
– region
– variety
– processing
– (farmer ?)
?

This would 
a) Reduce the time it takes to add new beans.
b) Guarantee some consistency within the data. The tendency to use of different aliases, languages and typos make it harder to analyse an exported data set. 

<img width="419" alt="Bildschirmfoto 2023-01-08 um 21 33 01" src="https://user-images.githubusercontent.com/107115698/211217727-1598b339-5341-4add-9dea-5458db819f37.png">

**Comment by Jan-mjm** [comment]
Thanks a lot. Take your time. :)

**Comment by graphefruit** [comment]
– county of origin
– region
– variety
– processing
– farmer
– farm
– certification
Is supported.
Delimiter : "," ";" "|" "space" is supported
