### ISSUE TITLE
Bug: Calculator for beverage quantity: decimal separator (iOS)

### ISSUE THREAD

**Issue by Jan-mjm** [graphefruit/Beanconqueror#466]
For entering the _total weight_, only a numpad providing a comma as decimal separator is available. The comma is then changed to a decimal point, when switching to the next input field.
However, then the input field for _server weight_ provides a full keyboard. If the user opts for a decimal comma as he was forced above, the comma is not replaced by a decimal point automatically, when tapping on _set weight_. Since the calculation of _beverage quantity_ requires the use of decimal points, data loss is the consequence (if the user does not spot that the preview is showing NaN).

I would advise opting for a numpad instead of full keyboard for _server weight_ as well. As reduncy, you could make the calculation  work with any decimal separator.
![IMG_29E811FD5A9C-1](https://user-images.githubusercontent.com/107115698/212303752-fde82c65-3126-4400-81b3-7ef6693ff07e.jpeg)

**Comment by graphefruit** [comment]
Hi there!
Thanks for opening the ticket

> I would advise opting for a numpad instead of full keyboard for _server weight_ as well. As reduncy, you could make the calculation work with any decimal separator.
Sadly i need to map the "," to a "." first, else the math functions are not correct.
After this app is written with cordova and not with a native framework, I cant customize the keyboard functionality like native frameworks do.
I'll have a look at the issue and whats possible to achieve.

**Comment by graphefruit** [comment]
Fixed in the next version.
