### ISSUE TITLE
Failing to setup dev environment

### ISSUE THREAD

**Issue by msp301** [graphefruit/Beanconqueror#476]
Hi,

I've been trying to setup Beanconqueror for development on Ubuntu 22.04 LTS but have been running into errors.

What Node version is Beanconqueror designed to run under?

I tried Node 18 and installed ionic as suggested by README but ran into Angular dependency conflicts. The README also suggests using NPM 6.14.11 so have tried Node 14 which was more successful.

At the moment I'm runniing:

```
npm install -g cordova@11.0.0
npm ci
npm run prepare
```

This highlighted that `package.json` has a dependency on `"@graphefruit/coffee-bluetooth-devices": "file:../../graphefruit-coffee-bluetooth-devices-0.0.1.tgz"`.

The file path moves outside of the repository. Was this dependency supposed to be included in the Beanconqueror repo? Please advise.

Thanks for your help :)

Martin

**Comment by graphefruit** [comment]
Hey Martin!
Please make sure to use dev branch, or the actual feature/graph branch.
Master is corrupt at the moment.

**Comment by krystxf** [comment]
it would be nice to maybe add `.nvmrc` file

**Comment by graphefruit** [comment]
thanks for the suggestion.
I've added the .nvmrc file @krystxf

**Comment by graphefruit** [comment]
I gonna close this ticket, after ticket is idle.
