### ISSUE TITLE
Support DiFluid R2

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#488]
Actually waiting for the API

**Comment by graphefruit** [comment]
Hey @mylesagray,
thats why I try to achieve :) 
Waiting still for the API, actually got told mid April

**Comment by mylesagray** [comment]
Exciting! Mine arrives tomorrow and I just set up your app with my Lunar, and am currently looking at how to get temp and pressure off my E61.  On Tue, Apr 4, 2023 at 20:18, Lars Saalbach ***@***.***> wrote:  
Hey @mylesagray,
thats why I try to achieve :)
Waiting still for the API, actually got told mid April

**Comment by ritterasdf** [comment]
also interested in this, @graphefruit, did DiFluid ever get back to you regarding the API?

**Comment by graphefruit** [comment]
@ritterasdf
The DiFluid Microbalance will be supported in the next update.
The R2 API is released aswell and the server integration was removed, but it will take some time to write the whole integration in BQ, because a new section needs to be created

**Comment by PaulHedonii** [comment]
Great news that Difluid R2 will be integrated! Please let me know if I could help testing the new section amd integration (on Android with R2 and Felicita Arc available.)

**Comment by graphefruit** [comment]
R2 integrated and tested, thanks to @randomcoffeesnob
