### ISSUE TITLE
Question: Why amount of water in After brewing?

### ISSUE THREAD

**Issue by Segelzwerg** [graphefruit/Beanconqueror#497]
I have a question. Why is the amount of water in the section After Brewing and not in Before Brewing?
Or did I miss something?

**Comment by graphefruit** [comment]
The amount of water is not fixed from the start.
You got a brew ratio like 1:17, (35g to 600g) but while you pour, you maybe stop on 589 or whatelse, therefore the amount of water is correct AFTER the brew.

Also Beanconqueror has two fields:
amount of water and beverage quantity
those both are used for filter

and beverage quantity is just used for espresso

**Comment by Segelzwerg** [comment]
Ok, I see. I haven't thought about it as I mainly use a Aeropress. You can't really measure the difference of what you poured and the result. At least not in easy way.

However thanks for clearing that up. In the end for me the importance is to keep track and try to reproduce recipes and the app definitely helps.

**Comment by graphefruit** [comment]
Measuring the difference (water amount vs beverage quantity) means, that you need to pour your liquid to another cup/server
You can activate the parameter to add a server name with a weight, which then can be used on calculation. 
On the Acaia Pearl there is a mode for the beverage mode, but this means to do everything step by step, so the scale can calculate.

**Comment by Segelzwerg** [comment]
> Measuring the difference (water amount vs beverage quantity) means, that you need to pour your liquid to another cup/server
> 
> You can activate the parameter to add a server name with a weight, which then can be used on calculation. 
> 
> On the Acaia Pearl there is a mode for the beverage mode, but this means to do everything step by step, so the scale can calculate.
> 
> 

Got it. Thanks. I'm rather new to home brewing and still use a scale without Bluetooth.

**Comment by graphefruit** [comment]
You're welcome!
I gonna close this ticket now
