### ISSUE TITLE
Display how much beans or brews are not shown after filtering

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#498]

**Comment by krystxf** [comment]
I can do that, where should the number be placed?

**Comment by graphefruit** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/6260244/221952262-72458fae-4eff-4208-8827-56772747b94d.png">
I think I'd go with this kinda solution, if a filter is active, and not all are showing, the displayed number is set on the tab.
Both on active and on archived.

Why is this even necessary?
Because some users change the rating in the settings and from going from like 100 to 70, and you got a rating from 76, this won't be displayed on default, because the rating is set from 0 to 70 by default (depending on the setting)

**Comment by krystxf** [comment]
Should there be also a number of beans/brews in the archive?

**Comment by graphefruit** [comment]
> Should there be also a number of beans/brews in the archive?
> 
> Also this could be an alternative

Definitiv also in the archive.
I like the idea of displaying the numbers of brews/beans always.

but if you're not filtering i'd just show:

Available
(2002)

when filtered:
Available
(1998/2002)

**Comment by graphefruit** [comment]
Please have a look on the infinite scroll.
AFAIK I take the different height elements for generating the height-property for the inifite scroll.
If the tab gets larger, we may need to add some pixels to the calculations - don't know out of the box

**Comment by krystxf** [comment]
It seems to me that scrolling works just fine (count is in the same component as a text)

**Comment by krystxf** [comment]
shouldn't filters reset on tab change (available/archived)? @graphefruit

**Comment by graphefruit** [comment]
> shouldn't filters reset on tab change (available/archived)? @graphefruit

Sorry for the late reply.
Filters should not change on tab change, and stay, when selected.
Each is individual for active and archived

**Comment by krystxf** [comment]
In that case PR is ready 🚀

**Comment by graphefruit** [comment]
> In that case PR is ready 🚀
Thank you!
I'll have a look at this next, week, actually I'm a bit busy in other things

**Comment by graphefruit** [comment]
Hey @krystxf  Sorry rough weeks! Will do a test & review at the weekend

**Comment by graphefruit** [comment]
Thank you @krystxf for your work, sadly it took me much longer then intented! But now its merged.
