### ISSUE TITLE
bad translations

### ISSUE THREAD

**Issue by krystxf** [graphefruit/Beanconqueror#500]
Both are in `develop` branch.

**1.** path: `Beans -> filter`
   ![image](https://user-images.githubusercontent.com/48121710/221711302-2bba2055-9711-45de-ba42-8c08bc1c4648.png)
   `Only favourites` would be more accurate in my opinion

**2.** missing translation - path: `menu -> Bean parameter -> Manage parameters -> Variety information -> Variety`
![image](https://user-images.githubusercontent.com/48121710/221713279-d31ab229-f242-4f85-8312-2b5aedf1e496.png)

**Comment by graphefruit** [comment]
Thanks for reporting.
I've changed the label, and added the missing one :)
