### ISSUE TITLE
Connect portafilter / xenia

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#503]

**Comment by LagaV** [comment]
Just out of curiosity as I‘m waiting on my Xenia DB upgrade…what is intended with this request?

**Comment by graphefruit** [comment]
> Just out of curiosity as I‘m waiting on my Xenia DB upgrade…what is intended with this request?

The general idea is that a preparation method, can be connected to a device.
Starting with the Xenia.

You can add your web API-URL for the xenia, and when you go and add a brew, you can choose which scripts you want to execute when starting the timer, and when the first drip is reached (when a scale is connected), aswell as to set your aiming liquid goal on a connected scale, when Beanconqueror would tell the Xenia to stop and flush

**Comment by LagaV** [comment]
Awesome…would be great if this becomes reality. Happy to test when my Xenia is upgraded (currently on waitlist for end of March). Hopefully this approach will work, as I haven‘t seen any reference for a script launch via the web interface.

**Comment by LagaV** [comment]
Ahhh…looks like this will be in 3.3 2.1 : 

 _Scripte werden direkt ohne Schalterzuweisung in der Übersicht ausführbar_

**Comment by graphefruit** [comment]
I'm actually with Holger directly in contact, and discussed the possibilities and the API's :)
