### ISSUE TITLE
NFC support

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#504]
Just had a similar thought as in here: [https://github.com/graphefruit/Beanconqueror/issues/67](https://github.com/graphefruit/Beanconqueror/issues/67). 

Having an NFC tag on each container being scanned with the mobile phone would launch Beanconqueror and start a „repeat“ for the last brew of this roast. 

Are there any updates to the NFC framework support, as this was the reason to shelf the original request?

**Comment by graphefruit** [comment]
The latest release of the plugin was 2020 - so a "bit" outdated.
I'd need to test it, and I'd need NFC-Tags at home myself for writing, which I don't have actually.

**Comment by LagaV** [comment]
I’m using 50ct tags (via eBay bought 10 as a set) to initiate homeautomation tasks (home assistant). 

Not sure if you would need to have an embedded NFC capability within the app. For iOS I leverage the Shortcuts automation functionality. This requires (published ?) URL handler capability for the intended app. So Beanconquerer would need a URL handler to start a new brew for a bean sort.

Advantage (within iOS) is, that the app not necessarily needs to be active if the tag is scanned.

**Comment by graphefruit** [comment]
The issues with this kind of solution is, you'd also need to know how to write an NFC Tag, and without any guidelines it will be a tricky topic.
Also you'd need to get the Bean-ID out of beanconqueror, so there need to be atleast one new option to show and copy maybe this kind of information, and generate an URL for tagging.

Yes you're right, there would be some ways of workaround, but wouldn't it be great to just "..." the beans -> Write NFC Tag?
Would be much more handy.

**Comment by reox** [comment]
This would be a great feature!

Basically, what you would have to do is:
1) Have dialog to initialize NFC Tags. In this dialog, a NDEF Message is written onto the tag, containing some random ID. The App keeps track of the IDs it has written
2) Link a tag to a bag. Here, one could also setup the brew type (espresso, filter etc) or defaults that should be used for this bean (specific grinder, water, ...)
2a) the tag is reused, while the bag is still in use. Maybe ask the user if the bag shall be archived or simply linked to the new bag.
3) Now the app knows which NDEF message is connected to which bag. Scanning the tag opens the app and starts the brew
4) When the bag is empty, the tag is removed from the bag and can be used for the next bag

btw, you do not need actual NFC Tags to test most of the functionality, QR codes containing the same URI as the NDEF message work as well ;)

@graphefruit I have a bag full of 15693 Icode Tags (coin shaped w/o glue). If you like I send you a few for free. I bought them years ago when I did a project with NFC and have not used them since them, except one tag for Home assistant (which works great, btw)

**Comment by reox** [comment]
As a workaround, if writing NFC Tags is too much effort, you can simply enable the URL handler. without resorting to NFC Reading/Writing.
At least on Android, the NFC Reading is done by the OS and only the URL is forwarded to the App. You could then do the following.  If an URL is presented ...
* that is not in the database of tags, add it
* that is in the database but not in use, ask on which bag to attach it
* that is in the database and attached to an coffee, start the brew

You could basically setup everything except reading/writing of tags. Tags can easily be written manually with another app.

**Comment by graphefruit** [comment]
@reox I'm not deep inside NFC Tags, but would it be possible to go like:
beanconqueror://NFC?beanId=1827318273461827365&brewId=81726364718?
Therefore I could just pass the internal UUID's, instead of referencing to a new ID which would need to be saved.

**Comment by LagaV** [comment]
On iOS I was able to write the sample tag to an NFC tag with „NF21 Tools“. When reading the text it launches Beanconquerer.  So seems operable. This approach might also work with QR codes as launcher.

**Comment by graphefruit** [comment]
> On iOS I was able to write the sample tag to an NFC tag with „NF21 Tools“. When reading the text it launches Beanconquerer. So seems operable. This approach might also work with QR codes as launcher.

Yes beanconqueror:// is the internal address, wich is already connected for bean-qr scans from roasteries. 
If the text is the same it doesn't matter if qr-code or nfc-tag, but NFC-Tags need a plugin to read NFC and a device which has NFC, qr-codes has already a build in scanner in BQ, or you can use normally the camera or plugins, so theres quite a "bit" of a difference.

**Comment by LagaV** [comment]
Generally to me the (NFC) URL approach seems a very good option, as this also launches the Beanconquerer app in one „swipe“. Having QR codes as a parallel option also makes sense. I would put NFC tags on dedicated bean containers and QR tags on in-use bean bags.

**Comment by graphefruit** [comment]
@LagaV @reox 
Its finally after updating to capacitor, and a new maintained cordova-plugin, this is coming.
You'll be able to write or read a NFC-tag for a coffee-bag.

**Comment by graphefruit** [comment]
@LagaV @reox In the next release it will be possible to read or write NFC-Chips for beans.
And choose the action: Add a brew, add a brew and choose preparation method, view bean or edit bean.

You can also choose QR-Code or NFC-Tag :)

**Comment by zshenker** [comment]
@graphefruit are there any particular types of NFC tags that will be supported by this feature/any in particular that you are testing with?

**Comment by graphefruit** [comment]
> @graphefruit are there any particular types of NFC tags that will be supported by this feature/any in particular that you are testing with?

I just bought me some: NFC Tag Ntag215 to test. (They are working)
If you have other NFC-Tags, I can pass you a development version APK if needed, so you could test

**Comment by zshenker** [comment]
@graphefruit I was planning to order some NTAG216 tags. I would be happy to test once I get them, but would you have an iOS build(TestFlight?)?

**Comment by graphefruit** [comment]
> @graphefruit I was planning to order some NTAG216 tags. I would be happy to test once I get them, but would you have an iOS build(TestFlight?)?

I have, but I do this via Google Firebase, please write me an email with your google-mail address so I can add you: info@beanconqueror.com

**Comment by satchafunkilus** [comment]
I noticed that when writing an NFC tag from within beanconqueror, I can only scan the tag from within the app, by tapping on the scan NFC tag icon. It won't do anything if I scan it from outside the app.

When I manually write the beanconqueror:// url to an NFC tag with e.g. NFC-Tools, I am able to scan it from the iOS Home screen and it will open beanconqueror directly. 

Is this on purpose? I feel like if I have to first open the app and tap on the scan icon, I might as well choose the beans manually in the app. There is no real advantage of using an NFC tag in that case.

**Comment by graphefruit** [comment]
@satchafunkilus Please have a look here: https://github.com/graphefruit/Beanconqueror/issues/893
