### ISSUE TITLE
Location of „Save“ button too close to iOS keyboard „Done“ (German: „Fertig“)

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#506]
No bug at all, just UI optimization….

Several times I have hit the „Save“ Button, while intending to finish the data entry / close the keyboard.

To resolve I see two options: 
a) Hide „Save“ while data entry/keyboard is active.
b) Move „Save“ further away, e.g. to the top.

![IMG_6424](https://user-images.githubusercontent.com/6940878/223657421-8def2a3c-3f76-4bea-87a6-d666042447f9.jpeg)

**Comment by graphefruit** [comment]
Hey @LagaV,
thanks for the ticket.
I've included the solution, that when the keyboard shows up the "speichern" and "abbrechen" will get hidden.
This is actually just build in for Brews and not for like beans etc.

Will be included in 6.4.

Thanks!
Lars
