### ISSUE TITLE
„Ground Coffee (gr)“ displayed value not updating when transferred from scale

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#507]
After hitting the scale button to update the „Ground Coffee (gr)“ value, the display is not reflecting the update. 

When entering manual update of this value the updated (scale provided) value is shown.

**Comment by graphefruit** [comment]
Can you please check, when you hit the button, and the value doesn't pop up, and you press on another textbox, if the value appears then?
I think its just a rendering issue, because of zone.js which I'd need to look again at

**Comment by LagaV** [comment]
The value changes, if I press on another textbox or open for edit. On top of this is the "no update" behaviour not happening all the time. I haven't detected any pattern, seems random.

**Comment by graphefruit** [comment]
Hey @LagaV,
I've made a wrapping solution, so the issue should be fixed with 6.4, else please open up another ticket.
Thanks!
Lars
