### ISSUE TITLE
Reset duration when repeating a brew

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#509]
I usually have multiple bags of espresso beans open at the same time. Thus, I use the "repeat brew" feature quite often, as I would like to "copy over" the grind and machine settings. However, I always have to manually reset the brew timer. If I forget to do that, the current brew is appended to the existing time...

Maybe I have just missed it, but is there some setting to reset the brew duration when a brew is repeated, i.e., similar to the pre-configuration ("Vorbelegung")?

**Comment by graphefruit** [comment]
Hey @reox,
in the actual development version 6.4 there will be the possibility to also define which parameters shall be repeated (all active by default) and can be reduced, so both use cases between "add" and "repeat" are then customizeable.

Also if an smart scale is attached for a new brew, and you try to start, you'll get a new popup reminds you to reset before you can start to reduce some of the issues (this popup won't happen if you have no scale connected)

**Comment by reox** [comment]
Oh nice! Looking forward to the next version 😍

**Comment by graphefruit** [comment]
Version 6.4 getting tested. This ticket was tested again, so I gonna close this one now.
