### ISSUE TITLE
Add option in "Brew Details" view to "Repeat"

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#510]
I often look into the "Brew Details" and if I found the right one, I want to repeat. No option in the "Brew details" - have to go back to the list view and use the "...". 

Would be great to have a repeat button within the "Brew Details".

**Comment by graphefruit** [comment]
Hey @LagaV,
thanks for opening the ticket.
I'll mark this for one of the next updates.
Won't be included in 6.4.

As a "workarround" you could set the list params you want to see, so you don't need to go into details, and from their you can repeat directly

**Comment by graphefruit** [comment]
This will be possible in the next release.
