### ISSUE TITLE
Details on supported pressure devices?

### ISSUE THREAD

**Issue by mylesagray** [graphefruit/Beanconqueror#514]
I see references in the app, and in the PRs to two different pressure devices that seem to be supported:

 - Popsicle
 - Direct Transducer

Is there any more information on these, where they can be found for purchase, etc?

**Comment by graphefruit** [comment]
Popsicle is a DIY Project (not by me), still in development.

The Direct Transducer would be this: https://transducersdirect.com/product-category/pressure-transducers/wireless-pressure-transducers/ but the refresh rates are just one second AFAIK - Integration is not tested.

With 6.4 the Pressensor is also official supported: https://pressensor.com/ - tested on my side and working

**Comment by mylesagray** [comment]
Ah hah! I was just looking at the Pressensor today, good to know there is a cheaper alternative to the SEP device!

**Comment by mylesagray** [comment]
My Pressensor should be arriving this week - is there a branch with the 6.4 patches in it I can build to test with?

**Comment by graphefruit** [comment]
The actual development branch is feature/graph.
Here you can also test #518

**Comment by graphefruit** [comment]
Closed.
