### ISSUE TITLE
Allow editing date

### ISSUE THREAD

**Issue by simons-plugins** [graphefruit/Beanconqueror#516]
I sometimes forget to enter a brew and when I then do it appears at the wrong time or date, messing up time since last caffeine. Can we adjust the date and time of a brew when we edit? 
Thanks

**Comment by graphefruit** [comment]
Hello @simons-plugins 
Changing the brew-date is already possible
Please go into menu: "Brewing parameters" -> "Manage parameters" -> Scroll down and activate "Custom brewing time".
Now you see a new field when adding a new brew to change the brew date by hand.

If you activated custom parameters for each preparation method, you need to enable this setting there aswell.

Hope that clarifies :)

**Comment by graphefruit** [comment]
I didn't hear a response, so I gonna close this issue.
If there is still something unclear, please open up a new ticket
