### ISSUE TITLE
Bug: Graph gets deleted when editing a brew

### ISSUE THREAD

**Issue by mylesagray** [graphefruit/Beanconqueror#518]
Given how the implementation of brew recording with scales (in my case: Acaia Lunar) the scale auto-tares after some time - causing the graph to get wiped out - so as a workaround I save the brew once it’s logged, turn off the scale and then edit the post-brew stuff like TDS.

However, when editing a brew that has a trace associated with it for some reason the trace is deleted as soon as you press the “Edit” button.

Is this a known issue, or am I logging incorrectly, or have my scales set up incorrectly?

**Comment by graphefruit** [comment]
Hey @mylesagray ,
sadly the modes are not supported on Beanconqueror, cause of closed API.
The auto-tare feature was reported some weeks ago by another user.
The solution is, that Beanconqueror will ask the user, if he really wants to tare and therefore delete the graph.

So therefore this is a known issue, and in 6.4 fixed :)

**Comment by mylesagray** [comment]
Good to hear, thanks Lars!I may dig into the undocumented portions of the API at a later stage.  On Tue, Apr 11, 2023 at 19:53, Lars Saalbach ***@***.***> wrote:  
Hey @mylesagray ,
sadly the modes are not supported on Beanconqueror, cause of closed API.
The auto-tare feature was reported some weeks ago by another user.
The solution is, that Beanconqueror will ask the user, if he really wants to tare and therefore delete the graph.
So therefore this is a known issue, and in 6.4 fixed :)

**Comment by graphefruit** [comment]
Some tickets to link for this:
#491 
#276 
#266 
#456

**Comment by graphefruit** [comment]
Closed.
