### ISSUE TITLE
Brew repeat | Reset output values

### ISSUE THREAD

**Issue by Mehlonious** [graphefruit/Beanconqueror#523]
When using brew repeat, it would for me be an be even faster workflow if all output values were reset, like brew timer and brew weight.

Awesome app, by the way. 👌🏻 Keep up the good work!

**Comment by graphefruit** [comment]
Hey @Mehlonious,
thanks for the feedback.
This will be possible with the new version 6.4.:
https://github.com/graphefruit/Beanconqueror/issues/468
You can customize the repeat logic for global or each preparation method, to define which params shall be preset or dismissed.

This won't match for fast-repeat.

**Comment by Mehlonious** [comment]
Ah! Perfect. 👌🏻

**Comment by graphefruit** [comment]
Closed, if there are still questions, please open up a new ticket
