### ISSUE TITLE
Request: bean details + heic images

### ISSUE THREAD

**Issue by Katzenstreu** [graphefruit/Beanconqueror#525]
Hi

I would like to enter some details in the bean section. If the espresso is an blended one I would like to add details like:

name of the cooperative
bean type (Arabica or Robusta) 
bean cleaning method (washed, puled, honey, natural, ...) 

It would be great to be able to use heic images (from Samsung). 

Best regards 
Tim

**Comment by graphefruit** [comment]
Hey @Katzenstreu,
Bean type, cooperative name or cleaning method all should be possible. 
Everything should be findable in the variety information tab.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/6260244/233799533-3d269726-7eb7-4b0d-a27d-565d29c30f20.png">
If you got a blend, you need to choose blend on the page, and then you'll get a next button:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6260244/233799556-5c3a7df9-897b-4b85-97c5-252f3e1d6d34.png">

Why HEIC Images are not supported, I don't know, did you try different locations, google photos or so on? 
I use a plugin to select images, and then save them as a jpg.

**Comment by Katzenstreu** [comment]
Thanks!
@HEIC images: I used the local storage and the failure is: "We found no file urls".

Best regards
Tim

**Comment by graphefruit** [comment]
Which device + os version you have on it?

**Comment by Katzenstreu** [comment]
Samsung Galaxy S21 FE with Android 13, One UI 5.1, G990BXXU4EWC7

**Comment by graphefruit** [comment]
Hey @Katzenstreu , look out for Version 7.0 of Beanconqueror which will be released (hopefully) this year.
Maybe the issues are fixed after I needed to update a lot of libraries

**Comment by graphefruit** [comment]
Hey @Katzenstreu,
after Version 7.4 is already it seems like this issue has been resolved.
If not please open up a new ticket.
Best
Lars
