### ISSUE TITLE
Flow data not recorded when starting timer from Acaia Lunar scales in v6.2 & 6.3

### ISSUE THREAD

**Issue by Daneish** [graphefruit/Beanconqueror#528]
Hi Lars,

I have found what appears to be a bug in v6.2/6.3 when a brew timer is started from my Acaia Lunar (original version) scales, and affecting both the iOS and Android versions of the app.

My workflow is to open Beanconquorer > Add brew, then tap the start timer button on my scales. This starts the timer displayed on the scales, and in v6.1.5 this would also start the flowrate graph progressing along the timeline. On completion, the weight, flow, graph, time, first coffee drip and beverage quantity would all be recorded.

However from v6.2, tapping the start timer button on the scales does not start the graph timeline; and the flow, graph and first coffee drip and beverage quantity are not recorded. The time and weight are still recorded.

Tapping the play button in the app does record all of the data, so it is just a problem when the timer is started from the scales.

My testing was done on:
- My main device, an iPad currently running iPadOS 16.4.1 and app v6.3. It had v6.2 and v6.1.5 installed in the past.
- An iPhone running iOS 16.4.1 and app v6.3.
- A Pixel running Android 12 and v6.3 from the Play Store, then v6.2 and 6.1.5 APKs from this repository.

I have attached three sets of logs:
- [iPad running 6.3 with two brews recorded, one starting timer from the scale where flow data was missing from brew, and a second starting timer from the app where data was captured.](https://github.com/graphefruit/Beanconqueror/files/11393024/v6.3.iPad.Start.from.Scales.%2B.Start.from.App.txt)
- [Pixel running 6.2 where timer was started from scale, but flow data was missing.](https://github.com/graphefruit/Beanconqueror/files/11393026/v6.2.Pixel.Start.from.Scales.txt)
- [Pixel running 6.1.5 where timer was started from the scale and data was captured.](https://github.com/graphefruit/Beanconqueror/files/11393025/v6.1.5.Pixel.Start.from.Scales.txt)

The Lunar scales have a few different Modes which auto-tare and auto-start the timer. I normally use "Mode 4 - Auto Tare Timer Starts with Flow Mode". I have also tested the more basic "Mode 2 - Dual Display Mode" which is all manual and have had the same results.

During most of my testing the Acaia Lunar scales was running firmware 2.6.013, but I have just updated it to the latest (2.6.017) and have had the same result (on iPad running v6.3).

In the past I have tended to use Beanconquorer while I'm dialling in a new batch of beans, then once it's dialled in, skip the app until I get my next bag of beans. Following the same workflow of pressing the button on the scales to start the timer works with or without using the app.

While there is certainly a workaround for this issue, I have found that having to change in my workflow has meant that I haven't been using the app for the past 6 months since v6.2 was released, and have been missing out on the insights of the app to help me dial in faster.

Lastly, I would just like to thank you for all of your dedication developing this excellent, useful and beautiful app!

While isolating the issue in the code is beyond my skillset, I would be more than happy to help out with any testing. Is this issue something that you would be able to help with?

**Comment by graphefruit** [comment]
Hello @Daneish,

thank you for opening the ticket and providing detailed information on this case.
Actually I'm on finishing Version 6.4, with a new graph and with some fixes there in the end aswell.

But I don't think this will 100% affect your described issues here.
Sadly, Beanconqueror does not support any of the modes which Acaia offers.
Acaias API's are proprietary, and are not open for Beanconqueror.
I just can tell you on this case to open up a bug ticket on Acaia, to ask them to help out Beanconqueror to also can support these modes.

This also affects on the button-pressed on the scale, because the API is not known how these information are gonna be transmitted to the Beanconqueror / or how they need to be listened too.

Anyhow the question is now, why this worked on 6.1.5 and not anymore on 6.2/6.3. 
I just have a Acaia Pearl S here on my side (self bought, not a given development device).
But I'll try to debug this case here.

I cant give you a time frame yet, because I'm actually on finishing Version 6.4.
I'll check it on this Version, when its been working - great, when not, I'll need to investigate after releasing this Version.

Also there are some ideas to to support modes on Beanconqueror itself, like to just start listening to weight changes, and start the timer itself in the end.
Or when removing a cup to stop the timer, but also here, cant give any timeframe, because the usecase is easy to read, but atleast for me hard to implement.

Best
Lars

**Comment by Daneish** [comment]
Thanks for getting back to me so quickly, I will look to get in contact with Acaia to ask them to provide more information on the API.

I did find that there was a commit in the Acaia SDK Android repository where [they mention set modes](https://github.com/acaia/acaia_sdk_android/commit/b3ca0b6973519dcc11d2c92ab2c689e95c2947bc). I’m really out of my depth here, but I don’t know if this is of any use to you?

In any case, please take your time with the 6.4 release, and I will look forward to when you’re free to look at this issue.

**Comment by graphefruit** [comment]
Hey @Daneish,

thanks for the info.

Sadly the SDK isn't a help for Beanconqueror, because it directly communicates via bluetooth and doesn't include the ACAIA SDK's.

I've requested several months ago, a cordova integration on acaia side, which would fix this issue aswell if they would go for it.

**Comment by graphefruit** [comment]
Hello @Daneish,
With Version 7.0 Beanconqueror has enabled own modes which will match to all scales, also a "weight for first weight change and then start the timer".
I gonna close this issue so.
The latest information about the scale integration can be found here: https://beanconqueror.gitbook.io/beanconqueror/resources/faq#why-are-smart-scale-modes-or-some-button-presses-not-supported

Best
Lars

**Comment by Daneish** [comment]
Hi Lars, I was just watching [James Hoffman’s video on coffee apps](https://youtu.be/PhdxP9lId6A?si=VA5-Xiht6cfr1Xbz) and saw that he shouted out Bean Conquerer, congratulations! That reminded me of this issue and I must have missed reply, my apologies. Thanks very much for getting back to me, I’ll try out the new version.

**Comment by Daneish** [comment]
Just one more message to say that the new start listening feature is great!

My workflow without the app was place cup on scales, press tare, switch espresso machine on and press timer start, then press stop the timer when the shot finishes.

Now when using the app, pressing start listening feature automatically tares (thanks), the vibration pump in my espresso machine works to automatically start the timer (thanks to the app), and it automatically stops (thanks to the app). This looks like it will improve the work flow a whole lot!

As you know the scales have auto start and stop and tare options, but they didn’t capture the pre-infusion time, and were annoying when weighing other things so I had turned them off. Thanks to the app, and the granular settings this has provided a whole extra set of functionality beyond what the scales could do natively.

Thank you for your amazing work!
