### ISSUE TITLE
Icons - Community Edition

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#531]
- [ ] hario dripper switch - https://www.hario-europe.com/products/v60-immersion-dripper-switch
- [ ] Trilocate - https://tricolate.com/  
- [ ] Cupping-spoon - https://pbs.twimg.com/profile_images/3749791746/bf1367e774be0b9371ac637ea133270a_400x400.png
- [ ] ROK-Espresso - https://caracda.de/products/rok-manuelle-espressomaschine-gc-classic?gclid=Cj0KCQiAw9qOBhC-ARIsAG-rdn7CU7JEXJU2KxxwZJuDJVyYhr54roJ3iGlv2IXylevhHEWHM_Za4loaAsq7EALw_wcB   
- [ ] December Dripper - https://www.wired.com/2017/10/review-december-dripper
- [ ]  Tornado Duo - https://brewista.co/products/tornado-duo-coffee-maker  
- [ ] Ratio Six Coffee Brewer - https://de.thedesignpart.com/products/ratio-six-matte-black-1?variant=40476104360115&currency=EUR&utm_source=google&utm_medium=cpc&utm_campaign=google+shopping&gclid=Cj0KCQiAw9qOBhC-ARIsAG-rdn5Ofx5D_vvsLalF-IC4gmzKpxHjWHYl0pqzpj6aehwNxEvoxUELLjAaAugHEALw_wcB  
- [ ] Cafec-Flower - https://cafec-jp.com/products/dripper/
- [ ] Tetra Dripper - https://kurasu.kyoto/products/munieq-tetra-drip 
- [ ] Pure Over - https://pureover.com/
- [ ] Hario W60 - https://www.hario-europe.com/products/w60-coffee-dripper
- [ ] Hario V60 Drip Decanter - https://www.hario-europe.com/products/hario-v60-drip-decanter
- [ ] Hario Woodneck - https://www.hario-europe.com/products/drip-pot-wood-neck
- [ ] 9Barista Espresso: - https://9barista.com/product/9barista-espresso-machine/
- [ ] NextLevel brewer - https://nextlevelbrewer.com/brewing-guide/ 
- [ ] ARAM Espresso-Maker -  https://www.aram.coffee/product-page/cafeteria-aram-base-de-a%C3%A7o 
- [ ] Loveramics - https://www.loveramics.com/
- [ ] Bee House Coffee Dripper - https://prima-coffee.com/equipment/zero-japan/bkk-15l-wh
- [ ] Trinity Zero - https://trinitycoffee.co/products/trinity-zero-the-coffee-press-with-purpose?variant=37894225035442  
- [ ] Trinity One - https://trinitycoffee.co/products/trinity-one-origin-decanter-brew-kit
- [ ] Simpliyfy Brewer -  https://simplify.coffee/products/brewer 
- [ ] Bonavita - https://bonavitaworld.com/products/wide-base-porcelain-immersion-dripper
- [ ] Melitta ePour -  https://www.roastmarket.de/melittar-filterkaffeemaschine-epour-1024-12-schwarz-gold.html
- [ ] Bialetti - 2 Sprouts - https://www.roastmarket.de/cilio-espresso-caffetiera-2-tassen.html?utm_source=s24&utm_medium=cpc&utm_content=942-2-054-00&s24clid=8231314a-eb28-4adc-9df6-e962836361da
- [ ] Beem-Pour-Over  -  https://beem.de/products/pour-over-filter-kaffeemaschine-mit-waage-glas
- [ ] Strietman - https://www.strietman.net/ct2
- [ ] Xenia-Portafilter -https://www.coffeecircle.com/de/p/xenia-espressomaschine?utm_source=awin&utm_medium=affiliate&utm_campaign=feed&awc=14018_1683571300_dcaf2e0acd64dc96e3a5d522c182ce11

**Comment by reox** [comment]
Don't forget the bripe: https://briping.com/ ;)

**Comment by reox** [comment]
I tried to create an image for the bripe. I found it hard to match the style of the other images, as the bripe is purely brass :D
Worth a PR?
![beanconqueror-preparation-bripe](https://github.com/graphefruit/Beanconqueror/assets/431045/782bfe32-dce7-4afe-a0c7-946c8e3d40e5)

**Comment by graphefruit** [comment]
After there weren't any icons created since the ticket opening, I gonna close this ticket now.

**Comment by graphefruit** [comment]
Hello @reox,
to be fair, the bripe doesn't hardly fit into the whole icon style from Beanconqueror actually.
The idea somehow was, that one/two? person are doing a complete rework of all graphics to have all the same look and feeling.

**Comment by reox** [comment]
No problem :) it was my first try and, as already said, was hard for me to adopt the existing style as the used materials are very different from white/silver.

I'm not sure if a rework of all icons would be necessary, I like the style!

**Comment by graphefruit** [comment]
> I'm not sure if a rework of all icons would be necessary, I like the style!
In the end for me its needed to fit somehow the overall style.
If we got like said 20 icons, and everyone has a different hand-writing, it somehow isn't feeling like a nice UI in the selection.

**Comment by reox** [comment]
> In the end for me its needed to fit somehow the overall style.
If we got like said 20 icons, and everyone has a different hand-writing, it somehow isn't feeling like a nice UI in the selection.

Yeah, I agree! Some people can copy a certain style easily, but I don't 😅
