### ISSUE TITLE
Machine inspection and service intervals

### ISSUE THREAD

**Issue by josuablejeru** [graphefruit/Beanconqueror#533]
Hi @graphefruit,

As Beanconqueror is my go-to for everything related to coffee, I was thinking it would be nice to manage any inspection and service intervals related to any Machine you might have in your arsenal.

This might be a nice list of thing to include in the Feature:
- Import existing Grinders and Methods
- Create Tasks in a checklist (ex. Clean ... on the first of every Month) 
  - Send push notifications if Tasks need to be performed
  - Mark tasks as resolved
  - Show an overview with last dates of resolved tasks

This would be nicely hidden in the "Menu" side-drawer.

If you consider this feature to be worthy of Beanconqueror, I would like to go and implement the feature myself. Let me know if you need any Mockups or something.

~ Josua

**Comment by graphefruit** [comment]
Hey @josuablejeru,
sorry for the late response.
The question for some kind of inspection and service intervals where done on a german forum.
Actually I'm on finishing the next version, after that I'll come back to this topic.

Have a great cup of coffee
Lars

**Comment by dharwardt** [comment]
This will be a great feature.

**Comment by graphefruit** [comment]
Hey @josuablejeru ,
release is done, and the bugfixes aswell :) 
I think its a great supplement in Beanconqueror, and it has been discussed in other forums / chats aswell.

Going for grinders and preparation methods is a good match.
Anyhow, it would be good to have like not only a specific date, also the possibility after X grams e.g. or X litre of water.

I'd appreciate some mockups for discussion, because it will be a new "dimension" like the water, green bean or roasting section.

I'd also go with a feature toggle in the settings like "Activate inspection/service interval area".
If you need any support, let me know.

Best
Lars

**Comment by dharwardt** [comment]
@graphefruit 
Is it possible to change the captions and/or layout depending on the selection of a drop down?

**Comment by dharwardt** [comment]
I mean the caption of the value after switching the inspection type (after x days, after x ml Coffee, after x grams of beans).

I'll do some scribbling. @graphefruit

**Comment by dharwardt** [comment]
My idea of the notification workflow:
![Screenshot_20230711-074318~2](https://github.com/graphefruit/Beanconqueror/assets/9380342/17f293d9-85c0-43ed-a104-f27a5f533ea7)
My idea of the statistic view:
![Screenshot_20230711-074339~2](https://github.com/graphefruit/Beanconqueror/assets/9380342/683152a3-82c2-4c96-afd6-275d6f4bff74)
Edit brewmethod view:
![Screenshot_20230711-074333~2](https://github.com/graphefruit/Beanconqueror/assets/9380342/fbf744b7-917b-43d8-86b5-9e4d0f0874a5)
Edit grinder view:
![Screenshot_20230711-074323~2](https://github.com/graphefruit/Beanconqueror/assets/9380342/5dc9828f-83d5-4037-8e46-484bb77bbd43)

So there are two questions: 
Is it possible so configure snooze?
Is it possible to configure different types of maintenance, like clean, intensive clean, descale)

Any other feedback?

**Comment by graphefruit** [comment]
Sorry for the delayed feedback.
Thank you for taking the time and doing the first scatches.

I would not see the service intervals in the edit of the grinder/preparation method.
I'd rather see it as an extra popover action like when pressing on "...", therefore it can be used more dynamic and have a better feature toggability.

What could be done is to do like add extra information in the list view like:
"Maintenance schedule in 5 days..." e.g. or give it an extra icon like "cleaned". 

The snooze function is important, but I would not go with it after each brew, I'd rather let the user choose: Next brew, next day, next week, custom e.g..

Specially for me: I'm doing 5 shots on my portafilter, if I'm getting a popup everytime I repeat I'd get crazy :D 

Also what needs to be checked: When I want a daily interval for like my portafilter, snoozing would maybe overwrite a daily routine in the end, else we'd go with 2 popups at a time.

For the service intervals, I think I'd split it and also support having multiple intervals set.

Grinders:
-> After X grind amount
-> After X days/weeks/months
-> Once?

Preparation method:
-> After X used amount of water
-> After X brews
-> After X days/weeks/months
-> Once?

Also give a name for the cleaning interval like "Descale after 90 days", "Clean after every brew". and so on.

Also I'd give the user the possibility to snooze all service intervals for this day/week/month (I know thats against this idea here) 

Statistics are cool but would be the least to come in my mind.

Also I'd go like on the Water area, having a dedicated page where all intervals can be seen, edited, etc. which references back to the "..." action of a preparation or grinder.

**Comment by dharwardt** [comment]
So regarding the service intervals menue, you mean in the menue where I can select between details, edit parameters etc.?
That sounds good.

The idea with the extra view is smart. Perhaps you can mark I done or snooze by long press or by swipeing away. 

Do you think the snooze is configurable in a menue or I can select the snooze time every time?

If you want so many intervals could be set. 
I think we need the separate area like water.

So there I can deactivate all intervals permanently or for a defined time.

So that my ideas so far. I'm happy to hear feedback.

**Comment by graphefruit** [comment]
Hey @dharwardt,

> So regarding the service intervals menue, you mean in the menue where I can select between details, edit parameters etc.?
Correct

> Do you think the snooze is configurable in a menue or I can select the snooze time every time?
I would go and choose snooze overall every time again, like the clock solution we got.

> I think we need the separate area like water.
Like you said, for me it would be a separate area.

Like we already did the first steps, I'd be defining how it should work inside BQ, but at all I'm not into developing this, so this would need a PR in the end.

**Comment by graphefruit** [comment]
This issue will be closed, after idle state.
