### ISSUE TITLE
Save/cancel button hidden under keyboard

### ISSUE THREAD

**Issue by Cancercookie** [graphefruit/Beanconqueror#538]
![Screenshot_2023-05-27-15-08-52-891_com beanconqueror app](https://github.com/graphefruit/Beanconqueror/assets/11654389/e29f4383-b3a5-4da6-845f-1f3e731f85ce)

it would be nice to be able to use the save button with the keyboard open, as is it's been hidden under the keyboard

**Comment by graphefruit** [comment]
Hey @Cancercookie,
it was realy hidden just in the latest update, to not accidentally hit "save"
https://github.com/graphefruit/Beanconqueror/issues/506

**Comment by Cancercookie** [comment]
I'll close the issue then, I didn't thought it was intentional
