### ISSUE TITLE
Xenia:  Record also xenia_pu_level_pw_control

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#580]
In a discussion (https://www.kaffee-netz.de/threads/xenia-dbl-diskussion-zu-scripten-switches-usw.150101/page-6#post-2246352)  reg. Xenia usage and profile development it was suggested, to also have the targeted pu_level_pw_control recorded.

**Comment by graphefruit** [comment]
I'll have a look, but this won't be something for the next version

**Comment by graphefruit** [comment]
After there hasn't been any questions/wishes from the Xenia users, this ticket will be closed as not planned.
If needed please open up a new ticket
Best
Lars
