### ISSUE TITLE
Xenia: Leverage brew temperature from machine setting / data 

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#584]

**Comment by graphefruit** [comment]
Do we talk about: `BG_SENS_TEMP_A` ?

**Comment by LagaV** [comment]
BG_SET_TEMP

**Comment by LagaV** [comment]
I was intending the „Brew temperature“ in „Before Brewing“

**Comment by graphefruit** [comment]
Just checked it `BG_SENS_TEMP_A` is the value.

**Comment by LagaV** [comment]
This is the actual temp. measurement, that flexes around the target value during a brew. Not wrong, but which value during a brew will you record. 

My thought was, for the time being just to take the currently dialed in brew group target temperature (BG_SET_TEMP)

**Comment by graphefruit** [comment]
Atleast on the test-instance I had, the BG_SET_TEMP was not transferred by the api `/overview` I don't know what needs to be done that this value will be provided

**Comment by LagaV** [comment]
Different call to http://xenia.local/overview_single

**Comment by graphefruit** [comment]
I see, didn't know this API was existing. Thanks
