### ISSUE TITLE
Repeat last brew per bean from bean view

### ISSUE THREAD

**Issue by reox** [graphefruit/Beanconqueror#586]
As I switch between beans regularly, I need to lookup the grinder settings for that bean. Currently, I scroll in the brew view to find the bean I want to use and press repeat brew. There is also the option to go to the beans page, get the list of brews and take the top one.
However, both processes are a bit slow in comparison to the following proposed workflow:

* go to the beans page
* for the bean select the menu
* have a button "repeat last brew"
* brew is repeated!

This would spare at least two clicks ;)

Furthermore, it could be integrated with the NFC Feature #504 - i.e., using a NFC tag / Bean QR Code could use the same URI to call repeat the last brew of that bean.

**Comment by reox** [comment]
The new "best brew" feature opens a new possibility: You could add a button that says "repeat last or best brew". If there is a best brew selected, repeat that one, otherwise the last brew is repeated.

**Comment by graphefruit** [comment]
This will be possible in the next update.
You'll get a new action button to repeat the last brew.
If you have one best brew, and one "normal" brew, you'll get another popover to choose "best brew or latest brew"
If the best brew is the latest one, you'd not get that overlay.

Best
Lars
