### ISSUE TITLE
Add option for repeat brews to clear notes section "on repeat"

### ISSUE THREAD

**Issue by LagaV** [graphefruit/Beanconqueror#593]
Xenia brew recipes are concatenated to the already exiting notes. Over time, with continues repeat of brews this list will get unnecessarily long. 

Therefor at least provide an option to clear out notes on a repeat action.

**Comment by graphefruit** [comment]
Hi @LagaV,
this is already possible:
Menu -> Brew parameters -> Define repeat parameters -> and uncheck the notes.

If you want, you can also customize your preparation method

**Comment by LagaV** [comment]
You're right. Sorry!
