### ISSUE TITLE
Allow "first drip time" parameter for custom brewing methods

### ISSUE THREAD

**Issue by EwanRoycroft** [graphefruit/Beanconqueror#598]
I've created a custom brewing method for my [phin filter](https://nguyencoffeesupply.com/blogs/news/vietnamese-coffee-phin-filter-stainless-steel), using the "pourover" preparation style. I want to be able to record the time for bloom, first drip, and final drip. However, I cannot add the time for first drip as this is only available for espresso. I cannot change the preparation style to "espresso" because this will block me from adding the "amount of water" parameter.

I propose that the "first drip time" parameter should not be locked for custom methods.

**Comment by graphefruit** [comment]
Hey @EwanRoycroft,
sorry I was busy because of the Android 13 Filesystem changes, which needed an emergency-release.
I need to look for the first-drip time and which side effects maybe come in the code when enabling it for all methods and not just espresso.

**Comment by graphefruit** [comment]
Hello @EwanRoycroft 
This will be possible in the next update.
To use this, you need to customize the preparation method and activate/deactivate the parameter therefore.
Globally this won't be possible, and still matches an espresso or filter method.

Best regards
Lars

**Comment by EwanRoycroft** [comment]
Excellent, thanks very much @graphefruit!
