### ISSUE TITLE
Support Microbalance Ti

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#637]

**Comment by alexw1982** [comment]
I just got the Ti but can’t connect - any way I can help? Not a dev though …

**Comment by graphefruit** [comment]
> I just got the Ti but can’t connect - any way I can help? Not a dev though …

The Microbalance Ti will be supported in a next upcoming Version, its not supported in V7.0.
It has some firmware issues which I reported back to DiFluid and they are working on it.

Can't give you an ETA actually.

**Comment by graphefruit** [comment]
The Ti will be implemented in the next version.

I've discussed some Firmware tweaks with DiFluid, they may will implement it later on, but we can start with this, it works so far :)
