### ISSUE TITLE
Average flow rate is about 10-20 times too high.

### ISSUE THREAD

**Issue by julian-klode** [graphefruit/Beanconqueror#643]
App version: 7.0.1
Scale: DiFluid Microbalance

I'm not sure I agree with the assessment that extracting 36g of coffee in 27 (38)s is a flow rate of 3.52 g/s:

![Screenshot_20240105-133328](https://github.com/graphefruit/Beanconqueror/assets/6325588/a898c7a7-8555-4ef3-a373-ee88e8436ff4)

Note the screen turned off in between and it disconnected...

But you can also look at yesterday's 35g in 25s being 6.47g/s
![Screenshot_20240105-134103](https://github.com/graphefruit/Beanconqueror/assets/6325588/be299f8e-180d-4a5e-a0cf-4bacf8de531a)

This is a DiFluid Microbalance

**Comment by julian-klode** [comment]
Data export if it helps https://drive.google.com/file/d/1-FtwT7tyYGXctFGEeq5MkrH99EUp6Mvt/view?usp=drivesdk

**Comment by julian-klode** [comment]
Yesterday's screenshot's graph was off, so here's a raw graph screenshot.

![Screenshot_20240105-134613](https://github.com/graphefruit/Beanconqueror/assets/6325588/3ccfa8b9-967f-4858-b10d-a842e751eb6d)

**Comment by graphefruit** [comment]
Hello @julian-klode,
thank you for the ticket.
I need to have a look here, its also an issue on a BlackCoffee.IO scales how it looks like

**Comment by graphefruit** [comment]
Hey @julian-klode,
could you please pass us the .XLS files for this brew/brews?
Thank you so much :)

**Comment by julian-klode** [comment]
I guess these should be it?

- [Beanconqueror_Flowprofile_Raw_16_50_42_12_01_2024.xlsx](https://github.com/graphefruit/Beanconqueror/files/13921061/Beanconqueror_Flowprofile_Raw_16_50_42_12_01_2024.xlsx)
- [Beanconqueror_Flowprofile_Raw_16_51_38_12_01_2024.xlsx](https://github.com/graphefruit/Beanconqueror/files/13921066/Beanconqueror_Flowprofile_Raw_16_51_38_12_01_2024.xlsx)

I also see the export from settings referred to flow profile json files which are sadly not in the zip alongside the top-level export, I'd have expected that to be a full "backup", oh well.

**Comment by graphefruit** [comment]
> I also see the export from settings referred to flow profile json files which are sadly not in the zip alongside the top-level export, I'd have expected that to be a full "backup", oh well.

This was a request on the Beanconqueror discord, back some months ago.
I've tested it.
The issue was that exporting a full backup took long, not at starting of entering data. 
But when its like me, after 4000 brews, and about 1000 brews tracked with a smart scale, it took about 10-15 minutes, and sometimes crashed.
So thats not a possibility in the end.
Thats why the data are exported in the Android_Data in a folder, or on iOS in the files folder

**Comment by graphefruit** [comment]
> I guess these should be it?
> 
> * [Beanconqueror_Flowprofile_Raw_16_50_42_12_01_2024.xlsx](https://github.com/graphefruit/Beanconqueror/files/13921061/Beanconqueror_Flowprofile_Raw_16_50_42_12_01_2024.xlsx)
> * [Beanconqueror_Flowprofile_Raw_16_51_38_12_01_2024.xlsx](https://github.com/graphefruit/Beanconqueror/files/13921066/Beanconqueror_Flowprofile_Raw_16_51_38_12_01_2024.xlsx)

Thank you, that looks good, I've passed them to Larry which will have a look.
Best
Lars

**Comment by lpecan** [comment]
To me this looks like a defective scale.

If you look at the raw data, the reports, it will often go up and down around a ceertain number and then make a big jump. See below, at about 0.25sec intevals.

20.9
22.8
22.3
22.2
23.2
23.5

So, over a few seconds, the reported changes look like this:

0.000
0.200
0.200
1.900
-0.500
-0.100
1.000
0.300
-0.100
0.400

There's no really good way to process this data. Just too much garbage. You'd have to write in so much smoothing that it would not really be reality anymore. Do other people have this problem with the microbalance? I sold mine.

**Comment by graphefruit** [comment]
I'll have a look with my Microbalance, but my flow values are also very strange

**Comment by julian-klode** [comment]
I also should be updating my firmware, it's still on 301 (sorry about that), I may have some data with fresh firmware tomorrow then. 

The problem may not just be the microbalance, arguably the bambino that's brewing the espresso is super lightweight and hence vibrates more than a big fancy machine.

**Comment by lpecan** [comment]
that makes sense...obviously impossible to fix that with software. You might need one of those scale stand things.

**Comment by graphefruit** [comment]
@julian-klode I've talked with DiFluid.
Could you please update to Firmware Version 0.0.8, and also set your Vibration Filter to atleast 3 and see how its working and paste your XLS files again?
Thanks & Have a great cup of coffee
Lars

**Comment by julian-klode** [comment]
I'm evaluating this one cup every 2 days (things are weird right now :D), but I upgraded to the latest version - 310 it says - and Beanconqueror did not receive measurements from the scale anymore. So I used DiFluid Cafe app, and it basically did not report measurements for 10s or so, then it did a huge jump straight to 20g and reset the time to 0s - which mirrors other reports saying vibration filtering isn't working well for them.

But I'll try again today and see if Beanconqueror now gets measurements. It's a long fight.

**Comment by graphefruit** [comment]
The new Firmware is out, the connection should work atleast again.

**Comment by graphefruit** [comment]
Hello @julian-klode,
We've made pretty good progress.
If you got an spare android-device, I could send you a sample APK to test out.
Just let me know and drop me an email: info@beanconqueror.com
Best
Lars

**Comment by graphefruit** [comment]
The calculation has been changed in 7.1. and should work. So i close this one now.

**Comment by julian-klode** [comment]
Sorry I got super distracted with cycling purchases and work, I'll go try 7.1 when it's out.

Thanks for working on this and sorry again.
