### ISSUE TITLE
Indonesian translation

### ISSUE THREAD

**Issue by ganjarsetia** [graphefruit/Beanconqueror#657]
I saw this PR https://github.com/graphefruit/Beanconqueror/pull/599 so if you don't mind, when Indonesian translation will be added?

**Comment by graphefruit** [comment]
Hey there @ganjarsetia,
sybond did a first translation, I've added him as a Lokalise translator, where some keys are missing.
If everything goes good I think with the 7.2 release (actually 7.1 is in development)

**Comment by ganjarsetia** [comment]
@graphefruit I see. He is not active again for translation, let me take over. I will only do JSON translation without testing the App, currently my support doesn't support ionic.

I saw your file `/src/assets/i18n/id.json`, just modify that file & create new PR right?

**Comment by graphefruit** [comment]
Hey @ganjarsetia,
please send me an E-Mail: info@beanconqueror.com.
Then I can add you a Lokalise account. Don't modify the file please, we got an extra translation service for this.

**Comment by ganjarsetia** [comment]
@graphefruit done. Check your inbox

**Comment by graphefruit** [comment]
Lokalise access given, and the translations are already pulled.
