### ISSUE TITLE
make project sponsorable 

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#66]
https://github.com/sponsors

**Comment by graphefruit** [comment]
Done, lets see what happends, this would be very nice.

**Comment by DeastinY** [comment]
it's not very visible right now, so maybe:
https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by graphefruit** [comment]
Thanks for the link, didn't know about this. 
Added my paypal link, the rest I couldn't fill out

**Comment by DeastinY** [comment]
![image](https://user-images.githubusercontent.com/5399476/76620095-ae922080-652c-11ea-89cb-32997f810d26.png)
perfect!
