### ISSUE TITLE
iOS: Space between scrolling list and bottom menu bar

### ISSUE THREAD

**Issue by eikecochu** [graphefruit/Beanconqueror#660]
- iPhone 13 Pro
- iOS 17.3.1
- Reproducible both in portrait and landscape mode
- I cannot reproduce this when running the app locally in my Chrome

![image](https://github.com/graphefruit/Beanconqueror/assets/325203/fe1380cc-0bfd-4e27-aa8d-1dd98933c108)

**Comment by graphefruit** [comment]
Hey @eikecochu,
thank you for reporting.
This sadly wasn't n issue before iOS 17.3, somehow iOS changed things and the calculcation is now different.
I can't even recreate this issue on using a normal Safari browser, just on an emulator or real device.
I'll make some tests but somehow I think this issue will be ....

**Comment by graphefruit** [comment]
This has been resolved in the next update
