### ISSUE TITLE
Fullscreen brew view is missing blooming/drip buttons after reset

### ISSUE THREAD

**Issue by eikecochu** [graphefruit/Beanconqueror#661]
To reproduce this issue:

1. Have no scale/pressure device etc connected
2. Create a new brew
4. Scroll down to brewing section
5. Click on expand icon to show time/buttons in full screen
6. Click on play
7. Click on preinfusion button (the one with the two coffee beans, on the left)
8. Click on the drip button (the middle one with the water drop)
9. Click on pause button
10. Click on reset button
11. Click on play button

I would expect preinfusion and drip button to show up again, but only the pause button is shown. To show the two buttons again, close fullscreen, then open again. Then all three buttons will show.

**Comment by Niffi** [comment]
Same here. 
After resetting the timer, the time information in the mentioned fields is also not reset to zero.

**Comment by graphefruit** [comment]
This has been resolved in the next update
