### ISSUE TITLE
Support for DiFluid Microbalance Ti Smartscale

### ISSUE THREAD

**Issue by classenj** [graphefruit/Beanconqueror#665]
DiFluid has released a new Smartscale, the [Microbalance Ti](https://digitizefluid.com/en-at/products/microbalance-ti)

It does not connect to the App (Version 7.0.1) while the R2 Extract and the normal Microbalance do.

**Comment by fhold** [comment]
that feature will come in 7.1

**Comment by classenj** [comment]
Ah just found it. #637 
Sorry about the duplicate issue
