### ISSUE TITLE
Write/Read NFC Tags

### ISSUE THREAD

**Issue by DeastinY** [graphefruit/Beanconqueror#67]
This is probably more of a feature for roasts.
I placed NFC tags on my coffee containers and store information there.
Reading/Writing those from the app directly would be amazing!
NFC is not standardized as part of any HTML specification, so not sure if ionic could do that

**Comment by graphefruit** [comment]
Could you please describe me a workflow, how you would like to see/use it? 

As part of the beans, or a new section?

**Comment by DeastinY** [comment]
Personally I'd say part of beans:

Instead of just creating beans also have an import button to import from tag.
Then within the bean have a save-to-nfc that writes some default information such as;
Name, date, degree, roaster, origin, .. best case have this configurable :joy: 
Photos won't possible I think, but the most important part would be name and date.

Not sure how much information would fit on a tag. Worst case there could be an alternative where it would just save a link to beanconqueror roast 45 and open that when you scan it. Can't be shared with anyone then though.

Workflow would be:
- Roast beans
- Enter details into BC
- Save bean data to NFC tag on bag of beans
- Share bean bag with all information with friend

Probably along the lines of the KaffeeNetz export?

**Comment by graphefruit** [comment]
Reading is possible with iOS11+
With iOS 13 Beta, its possible to write, but the official cordova plugins does not support them actual:
There is a fork, but don't think i gonna use this on start: https://github.com/iotize-sas/device-com-nfc.cordova

Else here goes the complete discussion: https://github.com/chariotsolutions/phonegap-nfc/issues/369

**Comment by DeastinY** [comment]
too bad there doesn't seem to be any more active development on phonegap-nfc :/
Still something to keep in mind for the future though maybe.
Thanks for looking into it!

**Comment by DeastinY** [comment]
Fixed in phonegap-nfc https://github.com/chariotsolutions/phonegap-nfc/pull/399

**Comment by graphefruit** [comment]
This feature was idle for long time, so closed.
If needed please reopen a new ticket.

**Comment by LagaV** [comment]
Just had a similar thought. Having an NFC tag on each container would launch Beanconqueror and start a „repeat“ for the last brew of this roast. Are there any updates to the NFC framework support?
