### ISSUE TITLE
Feature Request: DiFluid Microbalance Ti Support

### ISSUE THREAD

**Issue by peterstevensau** [graphefruit/Beanconqueror#670]
Hi,

Love your work guys! 

I purchased a DiFluid Microbalance Ti and it wasn't recognised by Bean Conquerer, could we please add support for this?

Let me know if there's anyway I can help or contribute, thanks.

**Comment by peterstevensau** [comment]
https://digitizefluid.com/en-au/products/microbalance-ti

**Comment by randomcoffeesnob** [comment]
Lars already implemented it - it will be part of version 7.1, coming soon:
https://github.com/graphefruit/Beanconqueror/issues/637

**Comment by graphefruit** [comment]
Hello @peterstevensau, like @randomcoffeesnob already said.
7.1 is support with the next update.
Have a great cup of coffee
Lars
