### ISSUE TITLE
Feature Suggestion: Dark Mode

### ISSUE THREAD

**Issue by peterstevensau** [graphefruit/Beanconqueror#672]
Just an idea guys, what about a dark mode theme for the app? 

Maybe an option to set the option to  light/dark/auto, whereby auto inherits the device/system settings for the device?

**Comment by graphefruit** [comment]
Hey @peterstevensau,
I've written an FAQ for this, please have a look here: https://beanconqueror.gitbook.io/beanconqueror/resources/faq#dark-mode-support

**Comment by graphefruit** [comment]
Closed, after no more questions where existing.
