### ISSUE TITLE
Sharing and importing Beans as JSON

### ISSUE THREAD

**Issue by zerweck** [graphefruit/Beanconqueror#689]
The reason for requesting this is I wanted to try to make Bing Copilot look at a roasters website and output a JSON that BC could import as a bean profile. GPT-4 and the likes should be good at understanding an example JSON and filling in fields with information that can be read from an unstructured description of the beans, but it is unlikely it will output a valid protobuffer encoding. As I looked at the sharing source, it seems there is an internal representation as JSON already, maybe I understood it wrong:
https://github.com/graphefruit/Beanconqueror/blob/ea4125ee39d553e38499ad052f80515c4445becf/src/services/shareService/share-service.service.ts#L51
Could this be used as an alternative way for a human- (and therefore LLM-) readable data format?

**Comment by graphefruit** [comment]
Hey @zerweck.
It could be possible to make it human readable.
The issue rather is, that the internal URL-format could not handle that long JSON-Strings to import them afterwards

**Comment by graphefruit** [comment]
After this topic has been idle, this ticket will be closed.
