### ISSUE TITLE
Brew ratio does not get calculated

### ISSUE THREAD

**Issue by Chais** [graphefruit/Beanconqueror#719]
It only shows `1/?`, even though beans in and water out are available. Even shows the amount of water out.  
![Screenshot_20240527-072340_Trebuchet.png](https://github.com/graphefruit/Beanconqueror/assets/1783098/40f8676b-16da-43ae-b419-ef54e69700fb)

Beans in is available, but doesn't appear to be used:  
![Screenshot_20240527-072446_Beanconqueror.png](https://github.com/graphefruit/Beanconqueror/assets/1783098/7b6b8608-8e0f-4f60-af53-3179ff561de2)

**Comment by Chais** [comment]
After I activated the ground coffee parameter the brew ratio shows up. However I noticed the default for that value doesn't take effect, so that may be part of the problem.

**Comment by graphefruit** [comment]
> After I activated the ground coffee parameter the brew ratio shows up. However I noticed the default for that value doesn't take effect, so that may be part of the problem.

Like you already found out.
Grind weight is used for the Brew Ratio calculcation.
Bean weight is just used for the retention e.g.

**Comment by Chais** [comment]
My point is if the ratio is based on ground coffee and its default value isn't taking effect, even if hidden/deactivated, maybe fixing that link will make the brew ratio work.  
After I activated the ground coffee value it didn't have a default value when I added a brew, even though it's configured to use the beans value, which is taken from the previous brew and _was_ properly filled.

**Comment by ruilya** [comment]
Took me a day before I'found this bug report and figured why I'm not getting brew ratio in the app. It would be convenient if there were an explanation inside the app

**Comment by graphefruit** [comment]
> Took me a day before I'found this bug report and figured why I'm not getting brew ratio in the app. It would be convenient if there were an explanation inside the app

Thank you for the feedback.
The Beans-amount is disabled by default, if this one is checked and grind-weight unchecked its this behaviour.
I'll add a label on the beans amount that this will not been taken for Brew-calculation.

Have a great cup of coffee
Lars
