### ISSUE TITLE
Add GitHub Action to run the tests on pushes and pull-requests

### ISSUE THREAD

**Issue by jjsil** [graphefruit/Beanconqueror#740]
Once #730 is resolved, add a GitHub Action to run the tests to prevent them from breaking.

I'm thinking of running on pushes and pull requests to `master` and `develop` to start with. Could then add `bugfix/*` perhaps?

**Comment by jjsil** [comment]
Example successful action: https://github.com/jjsil/Beanconqueror/actions/runs/9705454083

**Comment by graphefruit** [comment]
> I'm thinking of running on pushes and pull requests to `master` and `develop` to start with. Could then add `bugfix/*` perhaps?

Actually I just merge to master if I'm doing a new release with the release branch.
I think the develop branch aswell as maybe a bugfix or feature branch is the most used here.
But I think the best we could start simple and as more contributors come, we can then make more rules?

But anyway I like the idea to have automatic runs :)

**Comment by jjsil** [comment]
Successful run in `develop`!
https://github.com/graphefruit/Beanconqueror/actions/runs/10540643159
