### ISSUE TITLE
Add Pressure parameter on IOS app

### ISSUE THREAD

**Issue by chatbuddy21** [graphefruit/Beanconqueror#766]
Hope you can add “Pressure” parameter in bar on the While Brewing
![IMG_6134](https://github.com/user-attachments/assets/70ecda56-5e69-48cf-9467-e19904e9324c)

**Comment by graphefruit** [comment]
Hello @chatbuddy21,
theres already a parameter called "Profile" you could use this one to just say "9Bar Lever style" or something else.
Else "Pressure" would just be a number, where you could easily use the profile for.

**Comment by graphefruit** [comment]
After this seems like to be resolved, this ticket is closed. 
If needed please open up a new one.
Best & Thanks
Lars
