### ISSUE TITLE
Add Hario Pegasus

### ISSUE THREAD

**Issue by chatbuddy21** [graphefruit/Beanconqueror#791]
Is it possible to add the Hario Pegasus on the preparation method?

**Comment by graphefruit** [comment]
Hello @chatbuddy21 ,
thank you for the ticket.
All little sneaky icons where done back in the days by a person which left the product more then 3 years ago.
After then there hasn't been anyone up to styling the new icons to fitting the style, or reworking all to have a new fitting style.

But you can always just add a custom-preparation method and lay down a picture of it on your own
