### ISSUE TITLE
Improve Scale Switching Functionality for Different Brew Methods

### ISSUE THREAD

**Issue by m4r1k** [graphefruit/Beanconqueror#792]
I've been using Beanconqueror primarily for PO and recently started making espresso with a Flair 58. My PO scale, the Microbalancer TI, doesn't fit under the Flair's leg, so I purchased a BooKoo scale (thanks for the coupon code!).

While everything generally works well, I've encountered an issue when switching between brew methods. My routine involves starting with a PO and then making two espressos. Beanconqueror automatically connects to the last active scale, which is inconvenient when switching methods. 

Currently, I can manually connect the scale by going to Settings > BT Scale > Connect, but the option to reconnect the scale via "New Brew" > three dots > Reconnect Scale doesn't seem to function effectively.

Suggested Improvements

1. Enhance the scale-switching mechanism to allow seamless transition between different scales based on the selected brew method.
2. Ensure the "Reconnect Scale" feature works reliably without needing to navigate through settings.
3. Consider compatibility improvements for users with Microbalancer TI and BooKoo scales.

These enhancements would greatly improve the user experience for those using multiple brewing setups. Thank you!

**Comment by graphefruit** [comment]
Hi @m4r1k ,

thanks for the ticket and idea.

I'll try to break it down:
>Currently, I can manually connect the scale by going to Settings > BT Scale > Connect, but the option to reconnect the scale via "New Brew" > three dots > Reconnect Scale doesn't seem to function effectively.

Correct, reconnecting a scale, means that he disconnects from the actual one, and try to reconnect to this again, not to another scale, because he remembers the mac adress.

>Enhance the scale-switching mechanism to allow seamless transition between different scales based on the selected brew method.

This will be a very hard thing todo. 
Why? You'd need to connect a scale, and then say: This scale is for preparation 1 and 2, the other one for 3 and 4.
This is kinda an realy hard to understand situation, specially if you may create a preparation 5 -> You'd need to somehow select which scale you want to use there. And maybe even want to swap things out?
-> Things are getting unneeded complex.

>Ensure the "Reconnect Scale" feature works reliably without needing to navigate through settings.

Like written above, reconnect is exactly doing what reconnect means: Disconnect from the current one and connect to it again.

> Consider compatibility improvements for users with Microbalancer TI and BooKoo scales.

I dont understand this one, could you please elaborate more on this?

The thing what I could think about is to add to the three dots on the brew menu like: "Choose different scale" -> A popover will come, and will display actually all scales and disconnecting from the current one, then you could just connect to another scale, without going via the menu.
But also this would mean a new work on my side, because a popup to display which scales are found, aswell as making this in the code logic isn't existing now.

Have a great cup of coffee
Lars

**Comment by m4r1k** [comment]
> Hi @m4r1k ,
> 
> thanks for the ticket and idea.

👍 

> 
> I'll try to break it down:
> 
> > Currently, I can manually connect the scale by going to Settings > BT Scale > Connect, but the option to reconnect the scale via "New Brew" > three dots > Reconnect Scale doesn't seem to function effectively.
> 
> Correct, reconnecting a scale, means that he disconnects from the actual one, and try to reconnect to this again, not to another scale, because he remembers the mac adress.

Got it, effectively on Beanconqueror a scale is a BT Mac Address device. It just keeps track of the last connected one. All goes well for users with a single one. I wonder, do you happen to have stats around how many scales on average users have? Can you share the data or anyways use it to make a decision?

I just got myself into espresso, generally speaking scale for PO are bulkier to accomodate a large carafe while for spro thinner and smaller, at most for two espresso's cups.
There are a few around (e.g. Lunar) that can do both, but I feel like two scales would be the most common setup (another question would be whether both are connected but anyways)

> 
> > Enhance the scale-switching mechanism to allow seamless transition between different scales based on the selected brew method.
> 
> This will be a very hard thing todo. Why? You'd need to connect a scale, and then say: This scale is for preparation 1 and 2, the other one for 3 and 4. This is kinda an realy hard to understand situation, specially if you may create a preparation 5 -> You'd need to somehow select which scale you want to use there. And maybe even want to swap things out? -> Things are getting unneeded complex.

Indeed ignore this one entirely.

> 
> > Ensure the "Reconnect Scale" feature works reliably without needing to navigate through settings.
> 
> Like written above, reconnect is exactly doing what reconnect means: Disconnect from the current one and connect to it again.
> 
> > Consider compatibility improvements for users with Microbalancer TI and BooKoo scales.
> 
> I dont understand this one, could you please elaborate more on this?

Yeah I didn't know about the underline implementation. ignore this one too.

> 
> The thing what I could think about is to add to the three dots on the brew menu like: "Choose different scale" -> A popover will come, and will display actually all scales and disconnecting from the current one, then you could just connect to another scale, without going via the menu. But also this would mean a new work on my side, because a popup to display which scales are found, aswell as making this in the code logic isn't existing now.

How about an optional "Choose different scale" menu. It's still under the three dots section but in no way the default selection/screen and totally out of the way for users. The goal should be improving UX and not impacting any exciting user and workflow. Another option would be to keep track of more than one mac address. when Beanconqueror detects > 1 scales, the three dots manu could have multiple choices like "reconnect Scale X" and "reconnect Scale Y".

![IMG_6228](https://github.com/user-attachments/assets/d455a291-8b7a-4e28-982f-db9fae450e36)

> 
> Have a great cup of coffee Lars
Thanks Lars you too!

**Comment by graphefruit** [comment]
Hello @m4r1k ,
I did a good progress:
![image](https://github.com/user-attachments/assets/4cf85c1b-ef3e-4bc0-9535-7d1dad295156)

You'll get on the popover now the possibility to reconnect / disconnect or if nothing is connected to connect a specific device.
(Labels are not 100% correct right now)

**Comment by m4r1k** [comment]
Hey @graphefruit 
Wow this looks exactly like what I was expecting! I guess, it's scheduled for 7.6.0? Another great release

**Comment by graphefruit** [comment]
> Hey @graphefruit Wow this looks exactly like what I was expecting! I guess, it's scheduled for 7.6.0? Another great release

Hey @m4r1k, its scheduled for 7.6.0, but actually no timeframe given when it will be released.
