### ISSUE TITLE
Roast type not displayed in the Beans summary section

### ISSUE THREAD

**Issue by r00tbeet** [graphefruit/Beanconqueror#799]
Roast type field from Bean details is not displayed in the Beans summary section.
From the looks of it, the input field is of type BEAN_ROASTING_TYPE_ENUM but gets compared against ROASTS_ENUM. 

![IMG_F252EAE520C1-1](https://github.com/user-attachments/assets/9480dcc2-fe74-4756-9438-3d59a357a5f8)

![IMG_E6179141637E-1](https://github.com/user-attachments/assets/43be1c88-7d31-4305-a678-204266beb517)

**Comment by graphefruit** [comment]
Hey @r00tbeet,
the roast-type is a bit used twice, that are old technical depths since the start and I never started to change them.
The roast-type you see here is referencing "Light roast, new england roast" cinnamon roast... etc"

**Comment by graphefruit** [comment]
@r00tbeet you need to activate this parameter.
Menu -> Bean parameter -> Manage parameters -> "Roast type"

**Comment by r00tbeet** [comment]
Perfect, that resolves the issue for me.
Do you think it would be a good idea to make the above “Roast type” as the default?

**Comment by graphefruit** [comment]
>Do you think it would be a good idea to make the above “Roast type” as the default?
The normal roast-type is default, but not the american / cinnamon etc. roast.

I gonna close this ticket, after it has been resolved so :)
If there are any questions I'm happy to help
