### ISSUE TITLE
Timer function for Temperature surfing

### ISSUE THREAD

**Issue by wulfithewulf** [graphefruit/Beanconqueror#8]
As an enhancement, it would be really nice when there will be a timer for temperature surfing. 
It would stop when the normal timer would be started.

**Comment by graphefruit** [comment]
Thanks for reporting.
So to clearify:
Temperature timer: Start
Time: Start
Blooming: Start
.....

You press manually the temperature timer to start.
After 4 seconds you press 'start time' the temperature timer will stop, and the normal time will begin to tick from 1 beginning?

**Comment by wulfithewulf** [comment]
exactly, that would perfectly fit my use-case.

**Comment by graphefruit** [comment]
I'm on this feature request now.

**Comment by graphefruit** [comment]
Please check new release.
