### ISSUE TITLE
Stuck on white screen, won't start

### ISSUE THREAD

**Issue by llist2020** [graphefruit/Beanconqueror#802]
When starting the app, the logo shows and then it gets stuck on white screen. Any idea what might be happening? I'm using an Android 10 phone.
![Screenshot_20241001_103248_com.beanconqueror.app.jpg](https://github.com/user-attachments/assets/0e7c7c7c-ae5f-4d47-9b0a-500d3997613a)

Already tried clearing app data, reinstalling and manually giving all permissions.

**Comment by llist2020** [comment]
Got it to work by disabling internet access for the first start, but might be worth checking.

**Comment by graphefruit** [comment]
Hey @llist2020,
thanks for the ticket and great you found already a solution.
I don't know what would causing this, somehow I'd think you maybe got a custom rom installed and not a manufacturer one? Or having a specific device type with a specific rom?

**Comment by llist2020** [comment]
Hi, actually I did a factory reset recently, so it is a freshly installed Android 10 with Huawei EMUI 10.1.0.201 over it.

**Comment by graphefruit** [comment]
The issue has been found atleast, I close this topic, but we still can discuss here if needed.

**Comment by llist2020** [comment]
EMUI is an interface over the Android which comes as default on Huawei phones, so it may be a little different from standard Android OS. Anyways, I think it isn't worth the trouble for debugging if you don't have any Huawei phone on hand.
