### ISSUE TITLE
Unable to import brew graphs/flow profiles on Android 14

### ISSUE THREAD

**Issue by mehalter** [graphefruit/Beanconqueror#803]
I'm currently running Android 14 and am trying to transfer my data from one device to another. I followed the instructions described in the [FAQ](https://beanconqueror.com/faq.html) for "How to import/export on Android?"

I was able to migrate the app data as well as the exported `.zip` file, but upon import I am left with empty graphs. I look on the new device where the app data is and I can still see the `*_flow_profile.json` files but they don't seem to have been linked to the brews when importing the zip file when opening the app new.

It looks like each brew does think that there is a brew graph, but they are all empty:

![image](https://github.com/user-attachments/assets/fcf5b0bb-0335-4fd0-93c5-7f02a5cc90a6)

Any help is very much appreciated! Thank you so much in advance

**Comment by graphefruit** [comment]
Hey @mehalter,
you need to connect via ADB to your old phone and extract the beanconqueror folder. 
https://beanconqueror.gitbook.io/beanconqueror/how-to/backup-and-import-android-14

Have a look here.
Let me know if this helps.

The .ZIP File doesn't inherit image/graphs

**Comment by mehalter** [comment]
Ah yeah I knew the .zip file didn't contain the images/graphs and we needed to move over the `Android/data` direectory. Thanks for the link to the GitBook! I was looking for that. Using ADB worked great, very strange when I was doing the copying and pasting of the `Android/data` (not the ZIP) directory directly on the devices using a direct shell, it looked completely identical but it doesn't get loaded correctly apparently.

**Comment by graphefruit** [comment]
Great to hear it worked! Enjoy your new phone :)
