### ISSUE TITLE
Green bean weight value doesn't go down when roasted beans are consumed, even after bag is archived

### ISSUE THREAD

**Issue by sgharvey** [graphefruit/Beanconqueror#814]
My apologies if someone is still in the middle of working on this feature and doesn't need this info.

**Actions:**

1. Add green beans to green bean list, include weight data.
2. Add a bag from your green bean list (roast some) and indicate how much you roasted.
3. Add a brew using that coffee.
4. Notice that the weight of the bag has gone down by the weight of coffee brewed.
5. Notice that the weight of green beans has not gone down, although the roast count has gone up by 1.

**Expected Result**

Weight of green beans 'in stock' should go down when a bag is added from it, because doing that means you roasted them and they aren't green anymore. Even when I use up all of a bag that I have roasted and archive it, the green bean weight never decreases.

Thank you for making this software :)

**Comment by graphefruit** [comment]
Hello @sgharvey,
thanks for your ticket.

Could you may make a video about your workflow and routine and what exactly does not work?

From the coding side:
1. Add green bean with weight (250g lets say)
2. Roast bean  -> Put into the roast bean the used green bean weight
3. Roast bean has like 220g
4. Do a brew with 20 grams 
5. just 200g will be showing.

**Comment by sgharvey** [comment]
Demonstration of issue, 2:20 long
https://qiwi.gg/file/vLZ31109-screen-20241017-202140

The only thing that seems to not work is automatically subtracting weight of green beans roasted from the green bean 'cellar'. Once roasted, a bag does not behave any differently than a manually added bag.

Roast count behaves as expected, roast a bag and count goes up by 1. Delete a bag and count goes down by 1. Archive a roasted bag and the count remains the same.

**Comment by graphefruit** [comment]
> Demonstration of issue, 2:20 long
> https://qiwi.gg/file/vLZ31109-screen-20241017-202140

The video is not working somehow, please upload it on Youtube if possible.

>The only thing that seems to not work is automatically subtracting weight of green beans roasted from the green bean 'cellar'. Once roasted, a bag does not behave any differently than a manually added bag.

Please confirm that you enter your used green bean weight here (in the roast information tab on the roasted beans):
![image](https://github.com/user-attachments/assets/75a18935-1e54-4a52-a371-43607f8a0781)

**Comment by sgharvey** [comment]
I got it uploaded to YT, then read your comment and realized I missed out on that entire tab. Yup, that's the issue, the Roast Information tab was invisible to my brain for some reason. I realize it's very hard to cram this much functionality into a phone-sized interface, so I'll look more carefully in the future.

**Comment by graphefruit** [comment]
Great to hear! Enjoy your roasts :)
