### ISSUE TITLE
roast type is shown as dash in beans list view

### ISSUE THREAD

**Issue by ruilya** [graphefruit/Beanconqueror#824]
Although roast type is set to filter coffee, when listing all my beans roast type is displayed as `-`. I expected to see `Filter` instead

**Comment by graphefruit** [comment]
> Although roast type is set to filter coffee, when listing all my beans roast type is displayed as `-`. I expected to see `Filter` instead

Filter or Espresso is set in the Name 
<img width="167" alt="image" src="https://github.com/user-attachments/assets/4e9ae40a-f000-4706-9247-4387e8660e31">

The roast type you mean is american / cinnamon roast / etc. this is a different field which needs to be prefilled.

**Comment by ruilya** [comment]
Had to search for those titles you've given. Never heard of them before. Thanks for clarification

**Comment by graphefruit** [comment]
I gonna close this ticket so.
If needed please open up a new one.
