### ISSUE TITLE
Autocomplete for Coffee Type

### ISSUE THREAD

**Issue by HoustonPutman** [graphefruit/Beanconqueror#836]
Most of the text entry fields (that have frequently-repeated items) have a really good auto-complete built in. However I find my self misspelling "Cappuccino" a lot when filling out the "Coffee Type" section. It would be great if this was an easy fix to just enable it like a lot of the other fields.

**Comment by graphefruit** [comment]
Hello @HoustonPutman,
thanks for the ticket and the idea.
<img width="343" alt="image" src="https://github.com/user-attachments/assets/e46eaf83-5cb0-4a7b-9800-ffac7cc5df3d">
I think that is what you're searching for right?

It will be included in the next update.
I'll try to remove duplicated code and see if there is some more possibilites to add this :)

**Comment by HoustonPutman** [comment]
Yep, thanks!

**Comment by graphefruit** [comment]
The situation is, that I don't have a plugin for this, its own coded, and actually to much "code duplication"
