### ISSUE TITLE
Support Varia Aku Pro

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#839]

**Comment by vintner123** [comment]
Hi any progression on this? just got my aku pro scale ,when i try to connect it it cant find any scales but on searching the logs i can see it.
thankyou for all your work.

**Comment by graphefruit** [comment]
> Hi any progression on this? just got my aku pro scale ,when i try to connect it it cant find any scales but on searching the logs i can see it. thankyou for all your work.

Hello @vintner123, in the next upcoming release (8.0.0) the Varia PRO and the MICRO is connectable.
The Firmware actually has some flaws, why its not really useable with Beanconqueror right now, the needed changes has been passed to Varia.

Do you know on which firmware your scale is running?

Best
Lars

**Comment by vintner123** [comment]
thanks
my scales  have firmware v35.25.GL
thanks again
john

On 12 Dec 2024, at 21:04, Lars Saalbach ***@***.******@***.***>> wrote:



Hi any progression on this? just got my aku pro scale ,when i try to connect it it cant find any scales but on searching the logs i can see it. thankyou for all your work.

Hello @vintner123<https://github.com/vintner123>, in the next upcoming release (8.0.0) the Varia PRO and the MICRO is connectable.
The Firmware actually has some flaws, why its not really useable with Beanconqueror right now, the needed changes has been passed to Varia.

Do you know on which firmware your scale is running?

Best
Lars

**Comment by graphefruit** [comment]
One small update, I've received today morning a new test firmware.
After the first test its looking great!

**Comment by vintner123** [comment]
Thankyou
J.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Patnnn** [comment]
> Hello @vintner123, in the next upcoming release (8.0.0) the Varia PRO and the MICRO is connectable. The Firmware actually has some flaws, why its not really useable with Beanconqueror right now, the needed changes has been passed to Varia.
> 
> Do you know on which firmware your scale is running?
> 
> Best Lars

Do you mean the Varia AKU mini or is there also a micro now? I'm asking, because i bought the mini last week and haven't found a app that is working with it yet. And if yes, does the mini also have the same firmware issues?

Thanks for your work!

**Comment by graphefruit** [comment]
> Do you mean the Varia AKU mini or is there also a micro now? I'm asking, because i bought the mini last week and haven't found a app that is working with it yet. And if yes, does the mini also have the same firmware issues?
> 
> Thanks for your work!

There are three versions somehow:
Mini, Micro, Pro.

Beanconqueror is not live yet with the new release, so you won't be able to find it in Beanconqueror already.
What you can do is to download `nrfc-connect` app and see under which name the scale is reported.

I just asked VARIA about the mini and waiting for response

**Comment by Patnnn** [comment]
It's reported as AKU MINI SCALE in the nRF Connect App

**Comment by graphefruit** [comment]
> It's reported as AKU MINI SCALE in the nRF Connect App

So its a different scale.
I've the AKU Micro scale here

**Comment by Patnnn** [comment]
I could not find anything about the Micro on the Internet. Maybe it's still the same? Just to make sure, this is the one I have: https://www.variabrewing.com/collections/aku-new/products/varia-aku-mini-scale

**Comment by djgarrett21** [comment]
Latest firmware on Varia's website is 15.27. Not sure if they're using the same firmware across all scales (link goes to a generic AKU bluetooth page) but I was unsuccessful attempting to update my firmware on the AKU Pro following the instructions on Varia's website:
https://www.variabrewing.com/pages/aku-bluetooth

Using nRF Connect on iOS. 
Installed firmware: 35.25.GL

**Comment by graphefruit** [comment]
> I could not find anything about the Micro on the Internet. Maybe it's still the same? Just to make sure, this is the one I have: https://www.variabrewing.com/collections/aku-new/products/varia-aku-mini-scale

I can't tell you which are all the right versions.
There are 3 given, and I'd think the MINI-Scale is not the MICRO-Scale.


> Installed firmware: 35.25.GL
I can tell you that there will be a new needed firmware update to make it workable, I've got a latest beta-firmware which was working on my side then.

**Comment by Patnnn** [comment]
Hi @graphefruit,

I just tried the new 8.0.0 version of your app with the Varia Aku mini. Sadly it is not working with that scale yet. Have you got any reply from Aku regarding the mini? Maybe we should open a new issue for the Aku mini support.

**Comment by graphefruit** [comment]
> I just tried the new 8.0.0 version of your app with the Varia Aku mini. Sadly it is not working with that scale yet. Have you got any reply from Aku regarding the mini? Maybe we should open a new issue for the Aku mini support.

Hey @Patnnn,
the firmware is not officially released from Varia yet for the **PRO** and the **Micro** the Mini is actually not supported and I'm awaiting the feedback from Varia, I think they are also in holidays.
A new ticket for the Aku mini support, will be created if Varia wants to have this scale supported in blutooth terms.

**Comment by Patnnn** [comment]
Alright, thanks for the info!

**Comment by drmingva** [comment]
Hi, I'm interested in your support of the Aku Varia Pro model (https://www.variabrewing.com/products/varia-aku-pro) which is what this thread is titled. This scale is showing as having "new support" as of 8.0.0. Does that mean the Aku Varia Pro is fully supported now?

**Comment by graphefruit** [comment]
> This scale is showing as having "new support" as of 8.0.0. Does that mean the Aku Varia Pro is fully supported now?

Varia is soon releasing the beta-firmware where the last issues has been resolved.
FULLY support is a bit of a wide take.
Beanconqueror e.g. does NOT support any modes from the Varia (BQ does not support any modes on other scales aswell)

But the weight readout, timer start/stop/reset, aswell as taring the scale, so all needed basic functions are all working without issues on my side after I have one development scale.

**Comment by lukasrt** [comment]
FYI, Varia has released a new firmware update (25.13) for the AKU mini just recently. On the website it says the update includes Beanconqueror app integration.
After downloading and flashing, I can confirm that the connection is now working. The app recognizes the scale correctly as AKU mini and all basic functions seem to be there. With the previous firmware 25.11 the scale was not found, so it seems that the FW update makes the difference.

Actually all three scales, Pro, Mini and the old AKU Scale got new firmware updates that are labelled with "Added Pressonsor & Beanconqueror app connection", so probably all of them should be supported now.

**Comment by Patnnn** [comment]
> FYI, Varia has released a new firmware update (25.13) for the AKU mini just recently. On the website it says the update includes Beanconqueror app integration. After downloading and flashing, I can confirm that the connection is now working. The app recognizes the scale correctly as AKU mini and all basic functions seem to be there. With the previous firmware 25.11 the scale was not found, so it seems that the FW update makes the difference.
> 
> Actually all three scales, Pro, Mini and the old AKU Scale got new firmware updates that are labelled with "Added Pressonsor & Beanconqueror app connection", so probably all of them should be supported now.

Thank you for the info. I've also installed the firmware on the last weekend. I can confirm, that the connection is now working but it it's not very stable for me sadly. Do you have the same issue? Maybe it's related to my smartphone (Pixel 6 Pro)

**Comment by graphefruit** [comment]
Thanks for the test @lukasrt !

**Comment by graphefruit** [comment]
> Thank you for the info. I've also installed the firmware on the last weekend. I can confirm, that the connection is now working but it it's not very stable for me sadly. Do you have the same issue? Maybe it's related to my smartphone (Pixel 6 Pro)

Can you make sure that you have enabled the setting "keep scale connected when in background"? if not, please try it with this.

**Comment by Patnnn** [comment]
> > Thank you for the info. I've also installed the firmware on the last weekend. I can confirm, that the connection is now working but it it's not very stable for me sadly. Do you have the same issue? Maybe it's related to my smartphone (Pixel 6 Pro)
> 
> Can you make sure that you have enabled the setting "keep scale connected when in background"? if not, please try it with this.

Thanks for the reply, but it may have just been a problem with my phone. I changed a Bluetooth setting in the developer settings after I got the phone because it was having some problems with audio. I've now changed it back and restarted the phone. It seems to be stable now. I'll let you know if it changes :) I also noticed that the scale is reporting well over its rated 500g max capacity over Bluetooth. Which is a nice coincidence
