### ISSUE TITLE
Rate brew by categories 

### ISSUE THREAD

**Issue by jonasdiemer** [graphefruit/Beanconqueror#840]
Hi,

it's it possible to add ratings for different sub-tastes like body, acidity, bitterness and sweetness? Each with a scale of 1-5?

Cheers

**Comment by graphefruit** [comment]
> Hi,
> 
> it's it possible to add ratings for different sub-tastes like body, acidity, bitterness and sweetness? Each with a scale of 1-5?
> 
> Cheers

Hello there, 
thanks for the question.

What you can already do -> Brew -> "..." -> Cupping --> Schematic tasting -> It will show up the sweet marias cupping graph, is this what you're referencing for?

Best
Lars

**Comment by jonasdiemer** [comment]
Thanks, that's (more than) what I was looking for!
