### ISSUE TITLE
Suggestion: keep image when freezing coffee

### ISSUE THREAD

**Issue by agubelu** [graphefruit/Beanconqueror#857]
Hi there!

It's happened to me a few times that I add a coffee, give it an image, and let it rest for 2-3 weeks before freezing it. However, when I freeze it in Beanconqueror, the coffee image is lost and I have to select it again for the frozen one.

Would it be a good idea to copy the previous image when freezing a coffee?
Another option could be to copy the image only when you're freezing the whole bag.

Thanks for your consideration and Merry Christmas!

**Comment by graphefruit** [comment]
Hello @agubelu,
sorry for the late replay.
What you can do: If you freeze the whole package: Just edit the bean -> goto the freeze tab and enter your freeze date -> the image will be kept.

Maybe as a work around what I can do if someone opens the popup and freezes the whole bean without a brew beeing done, I just do the same as above.

The situation why images are not copied to a frozen one is:
Think about a 250g bag, you freeze with 10g each -> 25 frozen entries.

If you set an image with like 3mb, you'd get  -> 75mb in your file system.
Have a great start into 2025!
Best
Lars

**Comment by agubelu** [comment]
> What you can do: If you freeze the whole package: Just edit the bean -> goto the freeze tab and enter your freeze date -> the image will be kept.

Will do this, thanks for the tip!

**Comment by graphefruit** [comment]
> > What you can do: If you freeze the whole package: Just edit the bean -> goto the freeze tab and enter your freeze date -> the image will be kept.
> 
> Will do this, thanks for the tip!

Great to hear this helps!
Have a great new year!
Best
Lars

**Comment by agubelu** [comment]
You too!
