### ISSUE TITLE
Rename "Pressure Profile" to "Profile" to make it more versatile

### ISSUE THREAD

**Issue by silasg** [graphefruit/Beanconqueror#97]
Profiles for espresso can be based on pressure, flow or both.

Also, when using a dripper there are different "profiles", often called "brew advices", "recipes", "methods" and so on. Examples are named by their inventors like "Rao", "Kasuya", "Hoffmann" but could also are more descriptive like "2 pours", "3 pours and swirl" and so on.

I think  a single "Profile" field including a tiny hint how to use it in the placeholder text would meet the requirement to enter this kind of information very well.

Edit: seems that I can't add a "feature" label to the issue myself :(

**Comment by graphefruit** [comment]
Feature added.
