### ISSUE TITLE
Optionally shorten in/out Brew parameters in overview

### ISSUE THREAD

**Issue by silasg** [graphefruit/Beanconqueror#99]
Instead of having "Ground Coffee", "Coffee" and "Brew Rate" as 3 distinct fields in the list view of Brews, I'd like to optionally (new setting) display them as only one field "In/Out (BR)" with a value like "18g/36g (1:2)". This would save a lot of space, IMHO improve overview/ ascertainability and for a read-only view there is no need to keep those fields separated.

**Comment by silasg** [comment]
In #101 I added an example implementation of the feature described here.

**Comment by graphefruit** [comment]
I've added a solution in the next version
